package com.loracore.lang;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Компилятор LoraC -> Lora ASM.
 * Исправлена передача аргументов: теперь они сохраняются в память при входе в функцию.
 */
public class LoraCompiler {

    private final StringBuilder asm = new StringBuilder();
    private final Map<String, String> constants = new HashMap<>();
    private final Map<String, String> variables = new HashMap<>();

    // functionArgs больше не нужен для compileExpression, так как аргументы превращаются в переменные

    private int labelCounter = 0;
    private int varCounter = 0;

    private final Stack<String> loopEndStack = new Stack<>();

    public String compile(String sourceCode) {
        asm.setLength(0);
        constants.clear();
        variables.clear();
        loopEndStack.clear();
        labelCounter = 0;
        varCounter = 0;

        asm.append("; Generated by LoraCompiler\n");

        List<String> lines = preprocess(sourceCode);
        StringBuilder dataSection = new StringBuilder();

        asm.append("JMP main\n");

        parseFunctions(lines, dataSection);

        asm.append(dataSection);

        return asm.toString();
    }

    private List<String> preprocess(String source) {
        List<String> cleanLines = new ArrayList<>();
        String[] rawLines = source.split("\n");

        for (String line : rawLines) {
            line = line.trim();
            int commentIdx = line.indexOf("//");
            if (commentIdx >= 0) line = line.substring(0, commentIdx).trim();
            if (line.isEmpty()) continue;

            if (line.startsWith("const ")) {
                String content = line.substring(6).replace(";", "").trim();
                String[] parts = content.split("=");
                if (parts.length == 2) {
                    constants.put(parts[0].trim(), parts[1].trim());
                }
            } else {
                cleanLines.add(line);
            }
        }
        return cleanLines;
    }

    private void parseFunctions(List<String> lines, StringBuilder dataSection) {
        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i);

            if (line.startsWith("fn ")) {
                String decl = line.substring(3).replace("{", "").trim();
                int openParen = decl.indexOf('(');
                int closeParen = decl.indexOf(')');

                String funcName = decl.substring(0, openParen).trim();
                String argsStr = decl.substring(openParen + 1, closeParen).trim();

                variables.clear(); // Очищаем локальные переменные для новой функции

                asm.append("\n").append(funcName).append(":\n");

                // --- ИСПРАВЛЕНИЕ: Сохранение аргументов в память ---
                if (!argsStr.isEmpty()) {
                    String[] args = argsStr.split(",");
                    for (int j = 0; j < args.length; j++) {
                        String argName = args[j].trim();
                        // Создаем метку в памяти для аргумента
                        String label = "arg_" + funcName + "_" + argName + "_" + (++varCounter);

                        // Добавляем в .data
                        dataSection.append(label).append(":\n.data 0\n");

                        // Генерируем код: взять из регистра Rj и сохранить в label
                        // Используем R12 как временный регистр для адреса, чтобы не затереть R0-R3
                        asm.append("LDI R12, ").append(label).append("\n");
                        asm.append("ST R12, R").append(j).append("\n");

                        // Теперь компилятор знает этот аргумент как обычную переменную
                        variables.put(argName, label);
                    }
                }
                // ---------------------------------------------------

                int depth = 0;
                if (line.contains("{")) depth++;
                int j = i + 1;
                List<String> funcBody = new ArrayList<>();
                while (j < lines.size()) {
                    String l = lines.get(j);
                    if (l.contains("{")) depth++;
                    if (l.contains("}")) {
                        depth--;
                        if (depth == 0) break;
                    }
                    funcBody.add(l);
                    j++;
                }
                i = j;

                compileBlock(funcBody, dataSection);
                asm.append("RET\n");
            }
        }
    }

    private void compileBlock(List<String> lines, StringBuilder dataSection) {
        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i);

            if (line.startsWith("let ")) {
                handleLet(line, dataSection);
            } else if (line.startsWith("while")) {
                i = handleWhile(lines, i, dataSection);
            } else if (line.startsWith("if")) {
                i = handleIf(lines, i, dataSection);
            } else if (line.startsWith("mem[")) {
                handleMemWrite(line);
            } else if (line.equals("break;")) {
                if (!loopEndStack.isEmpty()) {
                    asm.append("JMP ").append(loopEndStack.peek()).append("\n");
                }
            } else if (line.equals("halt;")) {
                asm.append("HLT\n");
            } else if (line.contains("(") && line.endsWith(");")) {
                handleCall(line);
            } else if (line.contains("=")) {
                handleAssignment(line);
            }
        }
    }

    private void handleLet(String line, StringBuilder dataSection) {
        String content = line.substring(4).replace(";", "").trim();
        String[] parts = content.split("=", 2);
        String name = parts[0].trim();
        String expr = parts[1].trim();

        String label = "v_" + name + "_" + (++varCounter);
        variables.put(name, label);
        dataSection.append(label).append(":\n.data 0\n");

        compileExpression(expr, 0);

        asm.append("LDI R1, ").append(label).append("\n");
        asm.append("ST R1, R0\n");
    }

    private void handleAssignment(String line) {
        String content = line.replace(";", "").trim();
        String[] parts = content.split("=", 2);
        String name = parts[0].trim();
        String expr = parts[1].trim();

        if (!variables.containsKey(name)) {
            throw new IllegalArgumentException("Assignment to unknown variable: " + name);
        }

        compileExpression(expr, 0);

        String label = variables.get(name);
        asm.append("LDI R1, ").append(label).append("\n");
        asm.append("ST R1, R0\n");
    }

    private void handleMemWrite(String line) {
        String content = line.replace(";", "").trim();
        int closeBracket = content.indexOf(']');
        String addrExpr = content.substring(4, closeBracket).trim();
        String valExpr = content.substring(closeBracket + 1).replace("=", "").trim();

        // Адрес в R1
        compileExpression(addrExpr, 1);
        // Значение в R2
        compileExpression(valExpr, 2);

        asm.append("ST R1, R2\n");
    }

    private int handleWhile(List<String> lines, int startIdx, StringBuilder dataSection) {
        String header = lines.get(startIdx);
        String cond = header.substring(header.indexOf('(') + 1, header.lastIndexOf(')')).trim();

        String startLabel = "while_" + (++labelCounter);
        String endLabel = "endwhile_" + labelCounter;
        loopEndStack.push(endLabel);

        asm.append(startLabel).append(":\n");

        compileCondition(cond, endLabel, true);

        List<String> body = extractBlockLines(lines, startIdx);
        compileBlock(body, dataSection);

        asm.append("JMP ").append(startLabel).append("\n");
        asm.append(endLabel).append(":\n");

        loopEndStack.pop();
        return startIdx + body.size() + (header.contains("{") ? 0 : 1) + 1;
    }

    private int handleIf(List<String> lines, int startIdx, StringBuilder dataSection) {
        String header = lines.get(startIdx);
        String cond = header.substring(header.indexOf('(') + 1, header.lastIndexOf(')')).trim();

        String endLabel = "endif_" + (++labelCounter);

        compileCondition(cond, endLabel, true);

        List<String> body = extractBlockLines(lines, startIdx);
        compileBlock(body, dataSection);

        asm.append(endLabel).append(":\n");

        return startIdx + body.size() + 1;
    }

    private void handleCall(String line) {
        String content = line.replace(";", "").trim();
        int openParen = content.indexOf('(');
        String name = content.substring(0, openParen).trim();
        String argsRaw = content.substring(openParen + 1, content.indexOf(')')).trim();

        if (!argsRaw.isEmpty()) {
            String[] args = argsRaw.split(",");
            for (int i = 0; i < args.length; i++) {
                compileExpression(args[i].trim(), i);
            }
        }

        asm.append("CALL ").append(name).append("\n");
    }

    private void compileExpression(String expr, int targetReg) {
        expr = expr.trim();

        // 1. Поиск оператора верхнего уровня (+ или -)
        int bracketDepth = 0;
        int splitIndex = -1;
        char operator = ' ';

        for (int i = expr.length() - 1; i >= 0; i--) {
            char c = expr.charAt(i);
            if (c == ']') bracketDepth++;
            else if (c == '[') bracketDepth--;
            else if (bracketDepth == 0) {
                if (c == '+' || c == '-') {
                    splitIndex = i;
                    operator = c;
                    break;
                }
            }
        }

        if (splitIndex != -1) {
            String left = expr.substring(0, splitIndex).trim();
            String right = expr.substring(splitIndex + 1).trim();

            compileExpression(left, targetReg);
            compileExpression(right, targetReg + 1);

            if (operator == '+') {
                asm.append("ADD R").append(targetReg).append(", R").append(targetReg + 1).append("\n");
            } else {
                asm.append("SUB R").append(targetReg).append(", R").append(targetReg + 1).append("\n");
            }
            return;
        }

        if (expr.startsWith("mem[") && expr.endsWith("]")) {
            String inner = expr.substring(4, expr.length() - 1);
            compileExpression(inner, targetReg + 1);
            asm.append("LD R").append(targetReg).append(", R").append(targetReg + 1).append("\n");
            return;
        }

        if (isNumber(expr)) {
            int val = parseNumber(expr);
            if (val > 0xFFFF || val < -0x8000) {
                int upper = (val >>> 16) & 0xFFFF;
                int lower = val & 0xFFFF;

                asm.append("LUI R").append(targetReg).append(", ").append(upper).append("\n");
                if (lower != 0) {
                    asm.append("ORI R").append(targetReg).append(", ").append(lower).append("\n");
                }
            } else {
                asm.append("LDI R").append(targetReg).append(", ").append(val).append("\n");
            }
        } else if (constants.containsKey(expr)) {
            compileExpression(constants.get(expr), targetReg);
        } else if (variables.containsKey(expr)) {
            String label = variables.get(expr);
            asm.append("LDI R").append(targetReg + 1).append(", ").append(label).append("\n");
            asm.append("LD R").append(targetReg).append(", R").append(targetReg + 1).append("\n");
        } else {
            throw new IllegalArgumentException("Unknown term in expression: " + expr);
        }
    }

    private void compileCondition(String cond, String jumpLabel, boolean jumpIfFalse) {
        String[] parts = cond.split(" ");
        String left = parts[0];
        String op = parts[1];
        String right = parts[2];

        compileExpression(left, 0);
        compileExpression(right, 1);
        asm.append("CMP R0, R1\n");

        if (jumpIfFalse) {
            switch (op) {
                case "==" -> asm.append("JNZ ").append(jumpLabel).append("\n");
                case "!=" -> asm.append("JZ ").append(jumpLabel).append("\n");
                case ">"  -> { asm.append("JL ").append(jumpLabel).append("\n"); asm.append("JZ ").append(jumpLabel).append("\n"); }
                case "<"  -> { asm.append("JG ").append(jumpLabel).append("\n"); asm.append("JZ ").append(jumpLabel).append("\n"); }
            }
        }
    }

    private List<String> extractBlockLines(List<String> lines, int startIdx) {
        List<String> block = new ArrayList<>();
        int depth = 0;
        int i = startIdx;
        if (!lines.get(i).contains("{")) i++;

        for (; i < lines.size(); i++) {
            String line = lines.get(i);
            if (line.contains("{")) {
                if (depth > 0) block.add(line);
                depth++;
            } else if (line.contains("}")) {
                depth--;
                if (depth == 0) break;
                block.add(line);
            } else if (depth > 0) {
                block.add(line);
            }
        }
        return block;
    }

    private boolean isNumber(String s) {
        return s.matches("-?0x[0-9A-Fa-f]+") || s.matches("-?\\d+");
    }

    private int parseNumber(String s) {
        if (s.startsWith("0x") || s.startsWith("0X")) return Integer.parseUnsignedInt(s.substring(2), 16);
        return Integer.parseInt(s);
    }
}