package com.loracore.lang;

import com.loracore.lang.compiler.*;

import java.io.IOException;
import java.util.List;

/**
 * Фасад для модульного компилятора LoraC.
 */
public class LoraCompiler {

    /**
     * Компилирует код из строки (без поддержки внешних импортов).
     * @param sourceCode Исходный код.
     * @return ASM код.
     */
    public String compile(String sourceCode) {
        CompilerContext context = new CompilerContext();
        // Используем старый метод препроцессора для строки
        List<String> lines = Preprocessor.process(sourceCode, context);
        return internalCompile(lines, context);
    }

    /**
     * Компилирует файл с поддержкой импортов.
     * @param rootPath Путь к корневой папке исходников (например, "src/main/resources/assets/loracore/os/src").
     * @param mainFile Имя главного файла (например, "kernel.lc").
     * @return ASM код.
     */
    public String compile(String rootPath, String mainFile) throws IOException {
        CompilerContext context = new CompilerContext();
        // Используем новый метод препроцессора с поддержкой путей
        List<String> lines = Preprocessor.process(rootPath, mainFile, context);
        return internalCompile(lines, context);
    }

    /**
     * Внутренняя логика компиляции, общая для обоих методов.
     */
    private String internalCompile(List<String> lines, CompilerContext context) {
        CodeEmitter emitter = context.emitter;

        emitter.emitComment("Generated by LoraCompiler v3.1 (Strings & Imports)");

        // Точка входа
        emitter.emitJump("JMP", "main");

        FunctionParser functionParser = new FunctionParser(context);
        try {
            functionParser.parse(lines);
        } catch (LoraCompilerException e) {
            // Красивый вывод ошибки компиляции
            System.err.println("\n========== COMPILATION ERROR ==========");
            System.err.println(e.getMessage());
            System.err.println("=======================================\n");
            throw e;
        } catch (Exception e) {
            // Непредвиденные ошибки
            System.err.println("UNEXPECTED COMPILER ERROR: " + e.getMessage());
            e.printStackTrace();
            throw new RuntimeException(e);
        }

        return emitter.build();
    }
}