# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.3
loader_version=0.18.4
cca_version = 6.0.0
# Mod Properties
mod_version=1.3.0
maven_group=com.beykus.loracore
archives_base_name=loracore

# Dependencies
fabric_version=0.100.8+1.20.6
lwjgl_version=3.3.3
lwjgl_natives=natives-windows
fabric.loom.share.remap.cache=true