
pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
include("kernel", "ai-assistant", "terminal-app", "file-explorer-app", "device-test-app")

// Устанавливаем правильные имена проектов
rootProject.name = 'loracore'
project(':kernel').name = 'kernel'
project(':ai-assistant').name = 'ai-assistant'
project(':terminal-app').name = 'terminal-app'
project(':file-explorer-app').name = 'file-explorer-app'
project(':device-test-app').name = 'device-test-app'

