
pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
include("kernel", "ai-assistant", "terminal-app", "file-explorer-app", "device-test-app", "disk-manager-app")

// Устанавливаем правильные имена проектов
rootProject.name = 'loracore'
