
pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
include("kernel", "ai-assistant", "minimal-kernel")

// Устанавливаем правильные имена проектов
rootProject.name = 'loracore'
project(':kernel').name = 'kernel'
project(':ai-assistant').name = 'ai-assistant'
project(':minimal-kernel').name = 'minimal-kernel'
