; Generated by LoraCompiler v3.1 (Strings & Imports)
JMP main
; --- Function: init_gpu_driver ---
init_gpu_driver:
LDI R0, 1024
MOV R1, R0
LD R0, R1
LDI R1, v_base_3
ST R1, R0
LUI R0, 7
ORI R0, 59648
LDI R1, v_offset_4
ST R1, R0
LDI R2, v_base_3
LD R0, R2
LDI R2, v_offset_4
LD R1, R2
ADD R0, R1
LDI R1, g_gpu_regs_ptr_1
ST R1, R0
exit_init_gpu_driver_1:
RET
; --- Function: gpu_clear ---
gpu_clear:
LDI R12, arg_gpu_clear_color_2
ST R12, R0
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_5
ST R1, R0
LDI R2, arg_gpu_clear_color_2
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_clear_2:
RET
; --- Function: gpu_rect ---
gpu_rect:
LDI R12, arg_gpu_rect_x_3
ST R12, R0
LDI R12, arg_gpu_rect_y_3
ST R12, R1
LDI R12, arg_gpu_rect_w_3
ST R12, R2
LDI R12, arg_gpu_rect_h_3
ST R12, R3
LDI R12, arg_gpu_rect_color_3
ST R12, R4
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_6
ST R1, R0
LDI R2, arg_gpu_rect_x_3
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_y_3
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_w_3
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_h_3
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 20
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_color_3
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_rect_3:
RET
; --- Function: gpu_char ---
gpu_char:
LDI R12, arg_gpu_char_x_4
ST R12, R0
LDI R12, arg_gpu_char_y_4
ST R12, R1
LDI R12, arg_gpu_char_code_4
ST R12, R2
LDI R12, arg_gpu_char_color_4
ST R12, R3
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_7
ST R1, R0
LDI R2, arg_gpu_char_x_4
LD R0, R2
PUSH R0
LDI R2, v_regs_7
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_y_4
LD R0, R2
PUSH R0
LDI R2, v_regs_7
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_code_4
LD R0, R2
PUSH R0
LDI R2, v_regs_7
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_color_4
LD R0, R2
PUSH R0
LDI R2, v_regs_7
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 3
PUSH R0
LDI R2, v_regs_7
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_char_4:
RET
; --- Function: gpu_print ---
gpu_print:
LDI R12, arg_gpu_print_x_5
ST R12, R0
LDI R12, arg_gpu_print_y_5
ST R12, R1
LDI R12, arg_gpu_print_str_ptr_5
ST R12, R2
LDI R12, arg_gpu_print_color_5
ST R12, R3
LDI R2, arg_gpu_print_str_ptr_5
LD R0, R2
LDI R1, v_ptr_8
ST R1, R0
LDI R2, arg_gpu_print_x_5
LD R0, R2
LDI R1, v_cx_9
ST R1, R0
while_6:
LDI R0, 1
CMPI R0, 0
JZ endwhile_7
LDI R2, v_ptr_8
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_char_10
ST R1, R0
LDI R2, v_char_10
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_8
JMP endwhile_7
JMP endif_9
else_8:
endif_9:
LDI R2, v_cx_9
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_y_5
LD R0, R2
PUSH R0
LDI R2, v_char_10
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_color_5
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_9
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_9
ST R1, R0
LDI R2, v_ptr_8
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, v_ptr_8
ST R1, R0
JMP while_6
endwhile_7:
exit_gpu_print_5:
RET
; --- Function: gpu_print_hex ---
gpu_print_hex:
LDI R12, arg_gpu_print_hex_x_10
ST R12, R0
LDI R12, arg_gpu_print_hex_y_10
ST R12, R1
LDI R12, arg_gpu_print_hex_val_10
ST R12, R2
LDI R12, arg_gpu_print_hex_color_10
ST R12, R3
LDI R0, 28
LDI R1, v_i_11
ST R1, R0
LDI R2, arg_gpu_print_hex_x_10
LD R0, R2
LDI R1, v_cx_12
ST R1, R0
LDI R2, v_cx_12
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 48
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_12
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_12
ST R1, R0
LDI R2, v_cx_12
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 120
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_12
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_12
ST R1, R0
while_11:
LDI R2, v_i_11
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL endwhile_12
LDI R2, arg_gpu_print_hex_val_10
LD R0, R2
LDI R2, v_i_11
LD R1, R2
SHR R0, R1
LDI R1, 15
AND R0, R1
LDI R1, v_digit_13
ST R1, R0
LDI R0, 0
LDI R1, v_char_14
ST R1, R0
LDI R2, v_digit_13
LD R0, R2
PUSH R0
LDI R0, 10
MOV R1, R0
POP R0
CMP R0, R1
JG else_13
JZ else_13
LDI R0, 48
LDI R2, v_digit_13
LD R1, R2
ADD R0, R1
LDI R1, v_char_14
ST R1, R0
JMP endif_14
else_13:
LDI R0, 55
LDI R2, v_digit_13
LD R1, R2
ADD R0, R1
LDI R1, v_char_14
ST R1, R0
endif_14:
LDI R2, v_cx_12
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R2, v_char_14
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_12
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_12
ST R1, R0
LDI R2, v_i_11
LD R0, R2
LDI R1, 4
SUB R0, R1
LDI R1, v_i_11
ST R1, R0
JMP while_11
endwhile_12:
exit_gpu_print_hex_10:
RET
; --- Function: poll_keyboard ---
poll_keyboard:
LUI R0, 49
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_count_15
ST R1, R0
LDI R2, v_count_15
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL else_16
JZ else_16
LUI R0, 49
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_key_16
ST R1, R0
LDI R2, v_key_16
LD R0, R2
JMP exit_poll_keyboard_15
JMP endif_17
else_16:
endif_17:
LDI R0, 0
JMP exit_poll_keyboard_15
exit_poll_keyboard_15:
RET
; --- Function: stack_init ---
stack_init:
LDI R0, 28668
PUSH R0
POP R0
CALL set_stack_pointer
LDI R0, 10
PUSH R0
LDI R0, 30
PUSH R0
LDI R0, str_1
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
exit_stack_init_18:
RET
; --- Function: set_stack_pointer ---
set_stack_pointer:
LDI R12, arg_set_stack_pointer_addr_19
ST R12, R0
exit_set_stack_pointer_19:
RET
; --- Function: poke ---
poke:
LDI R12, arg_poke_addr_20
ST R12, R0
LDI R12, arg_poke_value_20
ST R12, R1
LDI R2, arg_poke_value_20
LD R0, R2
PUSH R0
LDI R2, arg_poke_addr_20
LD R0, R2
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_poke_20:
RET
; --- Function: peek ---
peek:
LDI R12, arg_peek_addr_21
ST R12, R0
LDI R2, arg_peek_addr_21
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_val_17
ST R1, R0
LDI R2, v_val_17
LD R0, R2
JMP exit_peek_21
exit_peek_21:
RET
; --- Function: pmm_init ---
pmm_init:
LDI R0, 0
LDI R1, v_i_18
ST R1, R0
while_23:
LDI R2, v_i_18
LD R0, R2
PUSH R0
LDI R0, 128
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_24
JZ endwhile_24
LDI R0, 16384
PUSH R0
LDI R2, v_i_18
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
PUSH R0
LDI R0, 0
PUSH R0
POP R1
POP R0
CALL poke
LDI R2, v_i_18
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_i_18
ST R1, R0
JMP while_23
endwhile_24:
LDI R0, 0
PUSH R0
LDI R0, 8
PUSH R0
POP R1
POP R0
CALL pmm_mark_region_used
LDI R0, 10
PUSH R0
LDI R0, 48
PUSH R0
LDI R0, str_2
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
exit_pmm_init_22:
RET
; --- Function: pmm_mark_region_used ---
pmm_mark_region_used:
LDI R12, arg_pmm_mark_region_used_start_25
ST R12, R0
LDI R12, arg_pmm_mark_region_used_count_25
ST R12, R1
LDI R0, 0
LDI R1, v_j_19
ST R1, R0
while_26:
LDI R2, v_j_19
LD R0, R2
PUSH R0
LDI R2, arg_pmm_mark_region_used_count_25
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_27
JZ endwhile_27
LDI R2, arg_pmm_mark_region_used_start_25
LD R0, R2
LDI R2, v_j_19
LD R1, R2
ADD R0, R1
PUSH R0
POP R0
CALL pmm_set_bit
LDI R2, v_j_19
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_j_19
ST R1, R0
JMP while_26
endwhile_27:
exit_pmm_mark_region_used_25:
RET
; --- Function: pmm_set_bit ---
pmm_set_bit:
LDI R12, arg_pmm_set_bit_page_idx_28
ST R12, R0
LDI R2, arg_pmm_set_bit_page_idx_28
LD R0, R2
LDI R1, 5
SHR R0, R1
LDI R1, v_word_idx_20
ST R1, R0
LDI R2, arg_pmm_set_bit_page_idx_28
LD R0, R2
LDI R1, 31
AND R0, R1
LDI R1, v_bit_off_21
ST R1, R0
LDI R0, 16384
PUSH R0
LDI R2, v_word_idx_20
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
LDI R1, v_addr_22
ST R1, R0
LDI R2, v_addr_22
LD R0, R2
PUSH R0
POP R0
CALL peek
LDI R1, v_val_23
ST R1, R0
LDI R0, 1
LDI R2, v_bit_off_21
LD R1, R2
SHL R0, R1
LDI R1, v_mask_24
ST R1, R0
LDI R2, v_addr_22
LD R0, R2
PUSH R0
LDI R2, v_val_23
LD R0, R2
LDI R2, v_mask_24
LD R1, R2
OR R0, R1
PUSH R0
POP R1
POP R0
CALL poke
exit_pmm_set_bit_28:
RET
; --- Function: pmm_test_bit ---
pmm_test_bit:
LDI R12, arg_pmm_test_bit_page_idx_29
ST R12, R0
LDI R2, arg_pmm_test_bit_page_idx_29
LD R0, R2
LDI R1, 5
SHR R0, R1
LDI R1, v_word_idx_25
ST R1, R0
LDI R2, arg_pmm_test_bit_page_idx_29
LD R0, R2
LDI R1, 31
AND R0, R1
LDI R1, v_bit_off_26
ST R1, R0
LDI R0, 16384
PUSH R0
LDI R2, v_word_idx_25
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
LDI R1, v_addr_27
ST R1, R0
LDI R2, v_addr_27
LD R0, R2
PUSH R0
POP R0
CALL peek
LDI R1, v_val_28
ST R1, R0
LDI R0, 1
LDI R2, v_bit_off_26
LD R1, R2
SHL R0, R1
LDI R1, v_mask_29
ST R1, R0
LDI R2, v_val_28
LD R0, R2
LDI R2, v_mask_29
LD R1, R2
AND R0, R1
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_30
LDI R0, 1
JMP exit_pmm_test_bit_29
JMP endif_31
else_30:
endif_31:
LDI R0, 0
JMP exit_pmm_test_bit_29
exit_pmm_test_bit_29:
RET
; --- Function: pmm_alloc_page ---
pmm_alloc_page:
LDI R0, 8
LDI R1, v_k_30
ST R1, R0
while_33:
LDI R2, v_k_30
LD R0, R2
PUSH R0
LDI R0, 4096
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_34
JZ endwhile_34
LDI R2, v_k_30
LD R0, R2
PUSH R0
POP R0
CALL pmm_test_bit
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_35
LDI R2, v_k_30
LD R0, R2
PUSH R0
POP R0
CALL pmm_set_bit
LDI R2, v_k_30
LD R0, R2
LDI R1, 12
SHL R0, R1
JMP exit_pmm_alloc_page_32
JMP endif_36
else_35:
endif_36:
LDI R2, v_k_30
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_k_30
ST R1, R0
JMP while_33
endwhile_34:
LDI R0, -1
JMP exit_pmm_alloc_page_32
exit_pmm_alloc_page_32:
RET
; --- Function: vmm_init ---
vmm_init:
LDI R0, 0
LDI R1, v_i_31
ST R1, R0
while_38:
LDI R2, v_i_31
LD R0, R2
PUSH R0
LDI R0, 1024
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_39
JZ endwhile_39
LDI R2, v_i_31
LD R0, R2
LDI R1, 4
MUL R0, R1
LDI R1, v_offset_32
ST R1, R0
LDI R0, 20480
LDI R2, v_offset_32
LD R1, R2
ADD R0, R1
LDI R1, v_addr_33
ST R1, R0
LDI R2, v_addr_33
LD R0, R2
PUSH R0
LDI R0, 0
PUSH R0
POP R1
POP R0
CALL poke
LDI R2, v_i_31
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_i_31
ST R1, R0
JMP while_38
endwhile_39:
LDI R0, 10
PUSH R0
LDI R0, 56
PUSH R0
LDI R0, str_3
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
exit_vmm_init_37:
RET
; --- Function: vmm_map_page ---
vmm_map_page:
LDI R12, arg_vmm_map_page_v_addr_40
ST R12, R0
LDI R12, arg_vmm_map_page_p_addr_40
ST R12, R1
LDI R12, arg_vmm_map_page_flags_40
ST R12, R2
LDI R2, arg_vmm_map_page_v_addr_40
LD R0, R2
LDI R1, 12
SHR R0, R1
LDI R1, v_idx_34
ST R1, R0
LDI R2, v_idx_34
LD R0, R2
PUSH R0
LDI R0, 1023
MOV R1, R0
POP R0
CMP R0, R1
JL else_41
JZ else_41
LDI R0, 0
JMP exit_vmm_map_page_40
JMP endif_42
else_41:
endif_42:
LDI R2, arg_vmm_map_page_p_addr_40
LD R0, R2
LDI R1, -4096
AND R0, R1
LDI R1, v_p_base_35
ST R1, R0
LDI R2, arg_vmm_map_page_flags_40
LD R0, R2
LDI R1, 4095
AND R0, R1
LDI R1, v_f_36
ST R1, R0
LDI R2, v_p_base_35
LD R0, R2
LDI R2, v_f_36
LD R1, R2
OR R0, R1
LDI R1, v_entry_37
ST R1, R0
LDI R2, v_idx_34
LD R0, R2
LDI R1, 4
MUL R0, R1
LDI R1, v_offset_38
ST R1, R0
LDI R0, 20480
LDI R2, v_offset_38
LD R1, R2
ADD R0, R1
LDI R1, v_target_39
ST R1, R0
LDI R2, v_target_39
LD R0, R2
PUSH R0
LDI R2, v_entry_37
LD R0, R2
PUSH R0
POP R1
POP R0
CALL poke
LDI R0, 1
JMP exit_vmm_map_page_40
exit_vmm_map_page_40:
RET
; --- Function: vmm_translate ---
vmm_translate:
LDI R12, arg_vmm_translate_v_addr_43
ST R12, R0
LDI R2, arg_vmm_translate_v_addr_43
LD R0, R2
LDI R1, 12
SHR R0, R1
LDI R1, v_idx_40
ST R1, R0
LDI R2, v_idx_40
LD R0, R2
LDI R1, 4
MUL R0, R1
LDI R1, v_offset_41
ST R1, R0
LDI R0, 20480
LDI R2, v_offset_41
LD R1, R2
ADD R0, R1
LDI R1, v_target_42
ST R1, R0
LDI R2, v_target_42
LD R0, R2
PUSH R0
POP R0
CALL peek
LDI R1, v_entry_43
ST R1, R0
LDI R2, v_entry_43
LD R0, R2
LDI R1, 1
AND R0, R1
LDI R1, v_present_44
ST R1, R0
LDI R2, v_present_44
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_44
LDI R0, 0
JMP exit_vmm_translate_43
JMP endif_45
else_44:
endif_45:
LDI R2, v_entry_43
LD R0, R2
LDI R1, -4096
AND R0, R1
LDI R1, v_p_base_45
ST R1, R0
LDI R2, arg_vmm_translate_v_addr_43
LD R0, R2
LDI R1, 4095
AND R0, R1
LDI R1, v_p_off_46
ST R1, R0
LDI R2, v_p_base_45
LD R0, R2
LDI R2, v_p_off_46
LD R1, R2
ADD R0, R1
LDI R1, v_res_47
ST R1, R0
LDI R2, v_res_47
LD R0, R2
JMP exit_vmm_translate_43
exit_vmm_translate_43:
RET
; --- Function: mm_init ---
mm_init:
LUI R0, 16
LDI R1, v_ptr_48
ST R1, R0
LUI R0, 16
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_ptr_48
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_ptr_48
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 0
PUSH R0
LDI R2, v_ptr_48
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LUI R0, 51966
ORI R0, 47806
PUSH R0
LDI R2, v_ptr_48
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_ptr_48
LD R0, R2
PUSH R0
LDI R0, 61440
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 10
PUSH R0
LDI R0, 10
PUSH R0
LDI R0, str_4
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
exit_mm_init_46:
RET
; --- Function: malloc ---
malloc:
LDI R12, arg_malloc_size_47
ST R12, R0
LDI R2, arg_malloc_size_47
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JG else_48
LDI R0, 0
JMP exit_malloc_47
JMP endif_49
else_48:
endif_49:
LDI R2, arg_malloc_size_47
LD R0, R2
LDI R1, 4
MOD R0, R1
LDI R1, v_rem_49
ST R1, R0
LDI R2, v_rem_49
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_50
LDI R2, arg_malloc_size_47
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, arg_malloc_size_47
ST R1, R0
JMP endif_51
else_50:
endif_51:
LDI R0, 61440
MOV R1, R0
LD R0, R1
LDI R1, v_curr_50
ST R1, R0
while_52:
LDI R2, v_curr_50
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ endwhile_53
LDI R2, v_curr_50
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_curr_size_51
ST R1, R0
LDI R2, v_curr_50
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_curr_free_52
ST R1, R0
LDI R2, v_curr_50
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_magic_53
ST R1, R0
LDI R2, v_magic_53
LD R0, R2
PUSH R0
LUI R0, 51966
ORI R0, 47806
MOV R1, R0
POP R0
CMP R0, R1
JZ else_54
LDI R0, 10
PUSH R0
LDI R0, 20
PUSH R0
LDI R0, str_5
PUSH R0
LUI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
HLT
JMP endif_55
else_54:
endif_55:
LDI R2, v_curr_free_52
LD R0, R2
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_56
LDI R2, v_curr_size_51
LD R0, R2
PUSH R0
LDI R2, arg_malloc_size_47
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JL else_58
LDI R2, arg_malloc_size_47
LD R0, R2
LDI R1, 16
ADD R0, R1
LDI R1, v_space_needed_54
ST R1, R0
LDI R2, v_curr_size_51
LD R0, R2
PUSH R0
LDI R2, v_space_needed_54
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JL else_60
JZ else_60
LDI R2, v_curr_50
LD R0, R2
LDI R1, 16
ADD R0, R1
LDI R1, v_new_block_ptr_55
ST R1, R0
LDI R2, v_curr_size_51
LD R0, R2
LDI R2, arg_malloc_size_47
LD R1, R2
SUB R0, R1
LDI R1, v_new_block_size_56
ST R1, R0
LDI R2, v_new_block_size_56
LD R0, R2
PUSH R0
LDI R2, v_new_block_ptr_55
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_new_block_ptr_55
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_curr_50
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LDI R2, v_new_block_ptr_55
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LUI R0, 51966
ORI R0, 47806
PUSH R0
LDI R2, v_new_block_ptr_55
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_malloc_size_47
LD R0, R2
PUSH R0
LDI R2, v_curr_50
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_new_block_ptr_55
LD R0, R2
PUSH R0
LDI R2, v_curr_50
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
JMP endif_61
else_60:
endif_61:
LDI R0, 0
PUSH R0
LDI R2, v_curr_50
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_curr_50
LD R0, R2
LDI R1, 16
ADD R0, R1
JMP exit_malloc_47
JMP endif_59
else_58:
endif_59:
JMP endif_57
else_56:
endif_57:
LDI R2, v_curr_50
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_curr_50
ST R1, R0
JMP while_52
endwhile_53:
LDI R0, 0
JMP exit_malloc_47
exit_malloc_47:
RET
; --- Function: free ---
free:
LDI R12, arg_free_ptr_62
ST R12, R0
LDI R2, arg_free_ptr_62
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_63
JMP exit_free_62
JMP endif_64
else_63:
endif_64:
LDI R2, arg_free_ptr_62
LD R0, R2
LDI R1, 16
SUB R0, R1
LDI R1, v_header_ptr_57
ST R1, R0
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_magic_58
ST R1, R0
LDI R2, v_magic_58
LD R0, R2
PUSH R0
LUI R0, 51966
ORI R0, 47806
MOV R1, R0
POP R0
CMP R0, R1
JZ else_65
LDI R0, 10
PUSH R0
LDI R0, 30
PUSH R0
LDI R0, str_6
PUSH R0
LUI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
JMP exit_free_62
JMP endif_66
else_65:
endif_66:
LDI R0, 1
PUSH R0
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_next_block_59
ST R1, R0
while_67:
LDI R2, v_next_block_59
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ endwhile_68
LDI R2, v_next_block_59
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_next_magic_60
ST R1, R0
LDI R2, v_next_magic_60
LD R0, R2
PUSH R0
LUI R0, 51966
ORI R0, 47806
MOV R1, R0
POP R0
CMP R0, R1
JZ else_69
LDI R0, 10
PUSH R0
LDI R0, 40
PUSH R0
LDI R0, str_7
PUSH R0
LUI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
HLT
JMP endif_70
else_69:
endif_70:
LDI R2, v_next_block_59
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_next_free_61
ST R1, R0
LDI R2, v_next_free_61
LD R0, R2
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_71
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_my_size_62
ST R1, R0
LDI R2, v_next_block_59
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_next_size_63
ST R1, R0
LDI R2, v_my_size_62
LD R0, R2
LDI R2, v_next_size_63
LD R1, R2
ADD R0, R1
LDI R1, v_new_size_64
ST R1, R0
LDI R2, v_new_size_64
LD R0, R2
PUSH R0
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_next_block_59
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_next_next_65
ST R1, R0
LDI R2, v_next_next_65
LD R0, R2
PUSH R0
LDI R2, v_header_ptr_57
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_next_next_65
LD R0, R2
LDI R1, v_next_block_59
ST R1, R0
JMP endif_72
else_71:
JMP endwhile_68
endif_72:
JMP while_67
endwhile_68:
exit_free_62:
RET
; --- Function: main ---
main:
CALL init_gpu_driver
LUI R0, 65312
ORI R0, 8224
PUSH R0
POP R0
CALL gpu_clear
LDI R0, 0
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, 480
PUSH R0
LDI R0, 16
PUSH R0
LUI R0, 65280
ORI R0, 128
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
LDI R0, 8
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, str_8
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
CALL stack_init
LDI R0, 10
PUSH R0
LDI R0, 20
PUSH R0
LDI R0, str_9
PUSH R0
LUI R0, 65484
ORI R0, 52428
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 100
PUSH R0
LDI R0, 20
PUSH R0
LDI R0, 28668
PUSH R0
LDI R0, -1
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
CALL pmm_init
CALL vmm_init
LDI R0, 10
PUSH R0
LDI R0, 64
PUSH R0
LDI R0, str_10
PUSH R0
LUI R0, 65484
ORI R0, 52428
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 120
PUSH R0
LDI R0, 64
PUSH R0
LDI R0, 20480
PUSH R0
LDI R0, -1
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
CALL mm_init
LDI R0, 10
PUSH R0
LDI R0, 80
PUSH R0
LDI R0, str_11
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
CALL pmm_alloc_page
LDI R1, v_p1_66
ST R1, R0
LDI R2, v_p1_66
LD R0, R2
PUSH R0
LDI R0, -1
MOV R1, R0
POP R0
CMP R0, R1
JZ else_74
LDI R0, 10
PUSH R0
LDI R0, 100
PUSH R0
LDI R0, str_12
PUSH R0
LUI R0, 65472
ORI R0, 49344
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 140
PUSH R0
LDI R0, 100
PUSH R0
LDI R2, v_p1_66
LD R0, R2
PUSH R0
LDI R0, -256
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LUI R0, 128
PUSH R0
LDI R2, v_p1_66
LD R0, R2
PUSH R0
LDI R0, 7
PUSH R0
POP R2
POP R1
POP R0
CALL vmm_map_page
LUI R0, 128
PUSH R0
POP R0
CALL vmm_translate
LDI R1, v_virt_67
ST R1, R0
LDI R2, v_virt_67
LD R0, R2
PUSH R0
LDI R2, v_p1_66
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_76
LDI R0, 10
PUSH R0
LDI R0, 116
PUSH R0
LDI R0, str_13
PUSH R0
LUI R0, 65280
ORI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
JMP endif_77
else_76:
LDI R0, 10
PUSH R0
LDI R0, 116
PUSH R0
LDI R0, str_14
PUSH R0
LUI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
endif_77:
JMP endif_75
else_74:
LDI R0, 10
PUSH R0
LDI R0, 100
PUSH R0
LDI R0, str_15
PUSH R0
LUI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
endif_75:
LDI R0, 10
PUSH R0
LDI R0, 140
PUSH R0
LDI R0, str_16
PUSH R0
LUI R0, 65365
ORI R0, 65365
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 156
LDI R1, v_cursor_y_68
ST R1, R0
LDI R0, 10
LDI R1, g_term_cursor_x_2
ST R1, R0
while_78:
LDI R0, 1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ endwhile_79
CALL poll_keyboard
LDI R1, v_key_69
ST R1, R0
LDI R2, v_key_69
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_80
LDI R2, g_term_cursor_x_2
LD R0, R2
PUSH R0
LDI R2, v_cursor_y_68
LD R0, R2
PUSH R0
LDI R2, v_key_69
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, g_term_cursor_x_2
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, g_term_cursor_x_2
ST R1, R0
LDI R2, g_term_cursor_x_2
LD R0, R2
PUSH R0
LDI R0, 470
MOV R1, R0
POP R0
CMP R0, R1
JL else_82
JZ else_82
LDI R0, 10
LDI R1, g_term_cursor_x_2
ST R1, R0
LDI R2, v_cursor_y_68
LD R0, R2
LDI R1, 16
ADD R0, R1
LDI R1, v_cursor_y_68
ST R1, R0
JMP endif_83
else_82:
endif_83:
JMP endif_81
else_80:
endif_81:
WAIT 10
JMP while_78
endwhile_79:
exit_main_73:
RET
g_gpu_regs_ptr_1:
.data 0
g_term_cursor_x_2:
.data 10
v_base_3:
.data 0
v_offset_4:
.data 0
arg_gpu_clear_color_2:
.data 0
v_regs_5:
.data 0
arg_gpu_rect_x_3:
.data 0
arg_gpu_rect_y_3:
.data 0
arg_gpu_rect_w_3:
.data 0
arg_gpu_rect_h_3:
.data 0
arg_gpu_rect_color_3:
.data 0
v_regs_6:
.data 0
arg_gpu_char_x_4:
.data 0
arg_gpu_char_y_4:
.data 0
arg_gpu_char_code_4:
.data 0
arg_gpu_char_color_4:
.data 0
v_regs_7:
.data 0
arg_gpu_print_x_5:
.data 0
arg_gpu_print_y_5:
.data 0
arg_gpu_print_str_ptr_5:
.data 0
arg_gpu_print_color_5:
.data 0
v_ptr_8:
.data 0
v_cx_9:
.data 0
v_char_10:
.data 0
arg_gpu_print_hex_x_10:
.data 0
arg_gpu_print_hex_y_10:
.data 0
arg_gpu_print_hex_val_10:
.data 0
arg_gpu_print_hex_color_10:
.data 0
v_i_11:
.data 0
v_cx_12:
.data 0
v_digit_13:
.data 0
v_char_14:
.data 0
v_count_15:
.data 0
v_key_16:
.data 0
str_1:
.data 83
.data 116
.data 97
.data 99
.data 107
.data 58
.data 32
.data 73
.data 110
.data 105
.data 116
.data 105
.data 97
.data 108
.data 105
.data 122
.data 101
.data 100
.data 32
.data 97
.data 116
.data 32
.data 48
.data 120
.data 48
.data 49
.data 70
.data 70
.data 70
.data 67
.data 0
arg_set_stack_pointer_addr_19:
.data 0
arg_poke_addr_20:
.data 0
arg_poke_value_20:
.data 0
arg_peek_addr_21:
.data 0
v_val_17:
.data 0
v_i_18:
.data 0
str_2:
.data 80
.data 77
.data 77
.data 58
.data 32
.data 66
.data 105
.data 116
.data 109
.data 97
.data 112
.data 32
.data 70
.data 105
.data 120
.data 101
.data 100
.data 0
arg_pmm_mark_region_used_start_25:
.data 0
arg_pmm_mark_region_used_count_25:
.data 0
v_j_19:
.data 0
arg_pmm_set_bit_page_idx_28:
.data 0
v_word_idx_20:
.data 0
v_bit_off_21:
.data 0
v_addr_22:
.data 0
v_val_23:
.data 0
v_mask_24:
.data 0
arg_pmm_test_bit_page_idx_29:
.data 0
v_word_idx_25:
.data 0
v_bit_off_26:
.data 0
v_addr_27:
.data 0
v_val_28:
.data 0
v_mask_29:
.data 0
v_k_30:
.data 0
v_i_31:
.data 0
v_offset_32:
.data 0
v_addr_33:
.data 0
str_3:
.data 86
.data 77
.data 77
.data 58
.data 32
.data 84
.data 97
.data 98
.data 108
.data 101
.data 32
.data 90
.data 101
.data 114
.data 111
.data 101
.data 100
.data 0
arg_vmm_map_page_v_addr_40:
.data 0
arg_vmm_map_page_p_addr_40:
.data 0
arg_vmm_map_page_flags_40:
.data 0
v_idx_34:
.data 0
v_p_base_35:
.data 0
v_f_36:
.data 0
v_entry_37:
.data 0
v_offset_38:
.data 0
v_target_39:
.data 0
arg_vmm_translate_v_addr_43:
.data 0
v_idx_40:
.data 0
v_offset_41:
.data 0
v_target_42:
.data 0
v_entry_43:
.data 0
v_present_44:
.data 0
v_p_base_45:
.data 0
v_p_off_46:
.data 0
v_res_47:
.data 0
v_ptr_48:
.data 0
str_4:
.data 77
.data 77
.data 58
.data 32
.data 72
.data 101
.data 97
.data 112
.data 32
.data 73
.data 110
.data 105
.data 116
.data 105
.data 97
.data 108
.data 105
.data 122
.data 101
.data 100
.data 0
arg_malloc_size_47:
.data 0
v_rem_49:
.data 0
v_curr_50:
.data 0
v_curr_size_51:
.data 0
v_curr_free_52:
.data 0
v_magic_53:
.data 0
str_5:
.data 77
.data 77
.data 32
.data 80
.data 65
.data 78
.data 73
.data 67
.data 58
.data 32
.data 72
.data 101
.data 97
.data 112
.data 32
.data 99
.data 111
.data 114
.data 114
.data 117
.data 112
.data 116
.data 105
.data 111
.data 110
.data 32
.data 100
.data 101
.data 116
.data 101
.data 99
.data 116
.data 101
.data 100
.data 33
.data 0
v_space_needed_54:
.data 0
v_new_block_ptr_55:
.data 0
v_new_block_size_56:
.data 0
arg_free_ptr_62:
.data 0
v_header_ptr_57:
.data 0
v_magic_58:
.data 0
str_6:
.data 77
.data 77
.data 32
.data 69
.data 82
.data 82
.data 79
.data 82
.data 58
.data 32
.data 73
.data 110
.data 118
.data 97
.data 108
.data 105
.data 100
.data 32
.data 112
.data 111
.data 105
.data 110
.data 116
.data 101
.data 114
.data 32
.data 105
.data 110
.data 32
.data 102
.data 114
.data 101
.data 101
.data 40
.data 41
.data 0
v_next_block_59:
.data 0
v_next_magic_60:
.data 0
str_7:
.data 77
.data 77
.data 32
.data 80
.data 65
.data 78
.data 73
.data 67
.data 58
.data 32
.data 78
.data 101
.data 120
.data 116
.data 32
.data 98
.data 108
.data 111
.data 99
.data 107
.data 32
.data 99
.data 111
.data 114
.data 114
.data 117
.data 112
.data 116
.data 101
.data 100
.data 33
.data 0
v_next_free_61:
.data 0
v_my_size_62:
.data 0
v_next_size_63:
.data 0
v_new_size_64:
.data 0
v_next_next_65:
.data 0
str_8:
.data 76
.data 111
.data 114
.data 97
.data 79
.data 83
.data 32
.data 118
.data 52
.data 46
.data 52
.data 32
.data 91
.data 77
.data 77
.data 85
.data 32
.data 68
.data 101
.data 98
.data 117
.data 103
.data 32
.data 77
.data 111
.data 100
.data 101
.data 93
.data 0
str_9:
.data 83
.data 116
.data 97
.data 99
.data 107
.data 32
.data 116
.data 111
.data 112
.data 58
.data 0
str_10:
.data 80
.data 97
.data 103
.data 101
.data 84
.data 97
.data 98
.data 108
.data 101
.data 32
.data 97
.data 116
.data 58
.data 0
str_11:
.data 72
.data 101
.data 97
.data 112
.data 58
.data 32
.data 82
.data 101
.data 97
.data 100
.data 121
.data 0
v_p1_66:
.data 0
str_12:
.data 65
.data 108
.data 108
.data 111
.data 99
.data 97
.data 116
.data 101
.data 100
.data 32
.data 80
.data 97
.data 103
.data 101
.data 58
.data 0
v_virt_67:
.data 0
str_13:
.data 86
.data 77
.data 77
.data 32
.data 84
.data 101
.data 115
.data 116
.data 58
.data 32
.data 80
.data 65
.data 83
.data 83
.data 0
str_14:
.data 86
.data 77
.data 77
.data 32
.data 84
.data 101
.data 115
.data 116
.data 58
.data 32
.data 70
.data 65
.data 73
.data 76
.data 0
str_15:
.data 65
.data 108
.data 108
.data 111
.data 99
.data 97
.data 116
.data 101
.data 100
.data 32
.data 80
.data 97
.data 103
.data 101
.data 58
.data 32
.data 70
.data 65
.data 73
.data 76
.data 69
.data 68
.data 0
str_16:
.data 83
.data 89
.data 83
.data 84
.data 69
.data 77
.data 32
.data 82
.data 85
.data 78
.data 78
.data 73
.data 78
.data 71
.data 0
v_cursor_y_68:
.data 0
v_key_69:
.data 0
