; Generated by LoraCompiler
JMP main

main:
CALL init_fonts
LUI R0, 255
ORI R0, 61440
LDI R1, v_pnp_1
ST R1, R0
LDI R2, v_pnp_1
LD R1, R2
LDI R2, 4
ADD R1, R2
LD R0, R1
LDI R1, v_count_2
ST R1, R0
LDI R1, v_pnp_1
LD R0, R1
LDI R1, 8
ADD R0, R1
LDI R1, v_current_3
ST R1, R0
LDI R0, 0
LDI R1, v_vram_base_4
ST R1, R0
LDI R0, 0
LDI R1, v_vram_size_5
ST R1, R0
while_1:
LDI R1, v_count_2
LD R0, R1
LDI R1, 0
CMP R0, R1
JL endwhile_1
JZ endwhile_1
LDI R2, v_current_3
LD R1, R2
LD R0, R1
LDI R1, v_type_6
ST R1, R0
LDI R1, v_type_6
LD R0, R1
LDI R1, 2
CMP R0, R1
JNZ endif_2
LDI R2, v_current_3
LD R1, R2
LDI R2, 4
ADD R1, R2
LD R0, R1
LDI R1, v_vram_base_4
ST R1, R0
LDI R2, v_current_3
LD R1, R2
LDI R2, 8
ADD R1, R2
LD R0, R1
LDI R1, v_vram_size_5
ST R1, R0
JMP endwhile_1
endif_2:
LDI R1, v_current_3
LD R0, R1
LDI R1, 16
ADD R0, R1
LDI R1, v_current_3
ST R1, R0
LDI R1, v_count_2
LD R0, R1
LDI R1, 1
SUB R0, R1
LDI R1, v_count_2
ST R1, R0
JMP while_1
endwhile_1:
LDI R1, v_vram_base_4
LD R0, R1
LDI R1, 0
CMP R0, R1
JNZ endif_3
HLT
endif_3:
LDI R1, 1280
LDI R3, v_vram_base_4
LD R2, R3
ST R1, R2
LDI R0, 0
LDI R1, v_offset_7
ST R1, R0
while_4:
LDI R1, v_offset_7
LD R0, R1
LDI R2, v_vram_size_5
LD R1, R2
CMP R0, R1
JG endwhile_4
JZ endwhile_4
LDI R1, v_vram_base_4
LD R0, R1
LDI R2, v_offset_7
LD R1, R2
ADD R0, R1
LDI R1, v_target_8
ST R1, R0
LDI R2, v_target_8
LD R1, R2
LUI R2, 65288
ORI R2, 4144
ST R1, R2
LDI R1, v_offset_7
LD R0, R1
LDI R1, 4
ADD R0, R1
LDI R1, v_offset_7
ST R1, R0
JMP while_4
endwhile_4:
LDI R0, 380
LDI R1, 240
LDI R2, 0
CALL plot_char
LDI R0, 430
LDI R1, 240
LDI R2, 28
CALL plot_char
LDI R0, 480
LDI R1, 240
LDI R2, 56
CALL plot_char
LDI R0, 530
LDI R1, 240
LDI R2, 84
CALL plot_char
HLT
RET

plot_char:
LDI R12, arg_plot_char_x_9
ST R12, R0
LDI R12, arg_plot_char_y_10
ST R12, R1
LDI R12, arg_plot_char_offset_f_11
ST R12, R2
LDI R0, 0
LDI R1, v_line_idx_12
ST R1, R0
while_5:
LDI R1, v_line_idx_12
LD R0, R1
LDI R1, 7
CMP R0, R1
JG endwhile_5
JZ endwhile_5
LDI R0, 8192
LDI R2, arg_plot_char_offset_f_11
LD R1, R2
ADD R0, R1
LDI R1, v_addr_in_font_13
ST R1, R0
LDI R1, v_line_idx_12
LD R0, R1
LDI R2, v_line_idx_12
LD R1, R2
ADD R0, R1
LDI R1, v_line_off_14
ST R1, R0
LDI R1, v_line_off_14
LD R0, R1
LDI R2, v_line_off_14
LD R1, R2
ADD R0, R1
LDI R1, v_line_off_14
ST R1, R0
LDI R2, v_addr_in_font_13
LD R1, R2
LDI R3, v_line_off_14
LD R2, R3
ADD R1, R2
LD R0, R1
LDI R1, v_pattern_15
ST R1, R0
LDI R0, 0
LDI R1, v_bit_idx_16
ST R1, R0
while_6:
LDI R1, v_bit_idx_16
LD R0, R1
LDI R1, 8
CMP R0, R1
JG endwhile_6
JZ endwhile_6
LDI R0, 0
LDI R1, v_draw_17
ST R1, R0
LDI R1, v_pattern_15
LD R0, R1
LDI R1, 127
CMP R0, R1
JL endif_7
JZ endif_7
LDI R0, 1
LDI R1, v_draw_17
ST R1, R0
LDI R1, v_pattern_15
LD R0, R1
LDI R1, 128
SUB R0, R1
LDI R1, v_pattern_15
ST R1, R0
endif_7:
LDI R1, v_pattern_15
LD R0, R1
LDI R2, v_pattern_15
LD R1, R2
ADD R0, R1
LDI R1, v_pattern_15
ST R1, R0
LDI R1, v_draw_17
LD R0, R1
LDI R1, 1
CMP R0, R1
JNZ endif_8
LDI R1, v_bit_idx_16
LD R0, R1
LDI R2, v_bit_idx_16
LD R1, R2
ADD R0, R1
LDI R1, v_block_x_18
ST R1, R0
LDI R1, v_block_x_18
LD R0, R1
LDI R2, v_block_x_18
LD R1, R2
ADD R0, R1
LDI R1, v_block_x_18
ST R1, R0
LDI R1, v_block_x_18
LD R0, R1
LDI R2, arg_plot_char_x_9
LD R1, R2
ADD R0, R1
LDI R1, v_block_x_18
ST R1, R0
LDI R1, v_line_idx_12
LD R0, R1
LDI R2, v_line_idx_12
LD R1, R2
ADD R0, R1
LDI R1, v_block_y_19
ST R1, R0
LDI R1, v_block_y_19
LD R0, R1
LDI R2, v_block_y_19
LD R1, R2
ADD R0, R1
LDI R1, v_block_y_19
ST R1, R0
LDI R1, v_block_y_19
LD R0, R1
LDI R2, arg_plot_char_y_10
LD R1, R2
ADD R0, R1
LDI R1, v_block_y_19
ST R1, R0
LDI R1, v_block_x_18
LD R0, R1
LDI R2, v_block_y_19
LD R1, R2
CALL draw_4x4
endif_8:
LDI R1, v_bit_idx_16
LD R0, R1
LDI R1, 1
ADD R0, R1
LDI R1, v_bit_idx_16
ST R1, R0
JMP while_6
endwhile_6:
LDI R1, v_line_idx_12
LD R0, R1
LDI R1, 1
ADD R0, R1
LDI R1, v_line_idx_12
ST R1, R0
JMP while_5
endwhile_5:
RET

draw_4x4:
LDI R12, arg_draw_4x4_bx_20
ST R12, R0
LDI R12, arg_draw_4x4_by_21
ST R12, R1
LDI R1, 1280
LD R0, R1
LDI R1, v_vbase_22
ST R1, R0
LDI R1, arg_draw_4x4_bx_20
LD R0, R1
LDI R2, arg_draw_4x4_bx_20
LD R1, R2
ADD R0, R1
LDI R1, v_off_x_23
ST R1, R0
LDI R1, v_off_x_23
LD R0, R1
LDI R2, v_off_x_23
LD R1, R2
ADD R0, R1
LDI R1, v_off_x_23
ST R1, R0
LDI R0, 0
LDI R1, v_off_y_24
ST R1, R0
LDI R0, 0
LDI R1, v_i_25
ST R1, R0
while_9:
LDI R1, v_i_25
LD R0, R1
LDI R2, arg_draw_4x4_by_21
LD R1, R2
CMP R0, R1
JG endwhile_9
JZ endwhile_9
LDI R1, v_off_y_24
LD R0, R1
LDI R1, 3840
ADD R0, R1
LDI R1, v_off_y_24
ST R1, R0
LDI R1, v_i_25
LD R0, R1
LDI R1, 1
ADD R0, R1
LDI R1, v_i_25
ST R1, R0
JMP while_9
endwhile_9:
LDI R1, v_vbase_22
LD R0, R1
LDI R2, v_off_y_24
LD R1, R2
ADD R0, R1
LDI R1, v_start_addr_26
ST R1, R0
LDI R1, v_start_addr_26
LD R0, R1
LDI R2, v_off_x_23
LD R1, R2
ADD R0, R1
LDI R1, v_start_addr_26
ST R1, R0
LDI R0, 0
LDI R1, v_row_27
ST R1, R0
while_10:
LDI R1, v_row_27
LD R0, R1
LDI R1, 4
CMP R0, R1
JG endwhile_10
JZ endwhile_10
LDI R2, v_start_addr_26
LD R1, R2
LDI R2, -1
ST R1, R2
LDI R2, v_start_addr_26
LD R1, R2
LDI R2, 4
ADD R1, R2
LDI R2, -1
ST R1, R2
LDI R2, v_start_addr_26
LD R1, R2
LDI R2, 8
ADD R1, R2
LDI R2, -1
ST R1, R2
LDI R2, v_start_addr_26
LD R1, R2
LDI R2, 12
ADD R1, R2
LDI R2, -1
ST R1, R2
LDI R1, v_start_addr_26
LD R0, R1
LDI R1, 3840
ADD R0, R1
LDI R1, v_start_addr_26
ST R1, R0
LDI R1, v_row_27
LD R0, R1
LDI R1, 1
ADD R0, R1
LDI R1, v_row_27
ST R1, R0
JMP while_10
endwhile_10:
RET

init_fonts:
LDI R0, 8192
LDI R1, v_b_28
ST R1, R0
LDI R2, v_b_28
LD R1, R2
LDI R2, 0
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 4
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 8
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 12
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 16
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 20
ADD R1, R2
LDI R2, 128
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 24
ADD R1, R2
LDI R2, 252
ST R1, R2
LDI R1, v_b_28
LD R0, R1
LDI R1, 28
ADD R0, R1
LDI R1, v_b_28
ST R1, R0
LDI R2, v_b_28
LD R1, R2
LDI R2, 0
ADD R1, R2
LDI R2, 124
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 4
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 8
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 12
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 16
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 20
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 24
ADD R1, R2
LDI R2, 124
ST R1, R2
LDI R1, v_b_28
LD R0, R1
LDI R1, 28
ADD R0, R1
LDI R1, v_b_28
ST R1, R0
LDI R2, v_b_28
LD R1, R2
LDI R2, 0
ADD R1, R2
LDI R2, 252
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 4
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 8
ADD R1, R2
LDI R2, 130
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 12
ADD R1, R2
LDI R2, 252
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 16
ADD R1, R2
LDI R2, 144
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 20
ADD R1, R2
LDI R2, 136
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 24
ADD R1, R2
LDI R2, 132
ST R1, R2
LDI R1, v_b_28
LD R0, R1
LDI R1, 28
ADD R0, R1
LDI R1, v_b_28
ST R1, R0
LDI R2, v_b_28
LD R1, R2
LDI R2, 0
ADD R1, R2
LDI R2, 16
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 4
ADD R1, R2
LDI R2, 40
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 8
ADD R1, R2
LDI R2, 68
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 12
ADD R1, R2
LDI R2, 68
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 16
ADD R1, R2
LDI R2, 124
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 20
ADD R1, R2
LDI R2, 68
ST R1, R2
LDI R2, v_b_28
LD R1, R2
LDI R2, 24
ADD R1, R2
LDI R2, 68
ST R1, R2
RET
v_pnp_1:
.data 0
v_count_2:
.data 0
v_current_3:
.data 0
v_vram_base_4:
.data 0
v_vram_size_5:
.data 0
v_type_6:
.data 0
v_offset_7:
.data 0
v_target_8:
.data 0
arg_plot_char_x_9:
.data 0
arg_plot_char_y_10:
.data 0
arg_plot_char_offset_f_11:
.data 0
v_line_idx_12:
.data 0
v_addr_in_font_13:
.data 0
v_line_off_14:
.data 0
v_pattern_15:
.data 0
v_bit_idx_16:
.data 0
v_draw_17:
.data 0
v_block_x_18:
.data 0
v_block_y_19:
.data 0
arg_draw_4x4_bx_20:
.data 0
arg_draw_4x4_by_21:
.data 0
v_vbase_22:
.data 0
v_off_x_23:
.data 0
v_off_y_24:
.data 0
v_i_25:
.data 0
v_start_addr_26:
.data 0
v_row_27:
.data 0
v_b_28:
.data 0
