; Generated by LoraCompiler v3.0 (Modular)
JMP main
; --- Function: main ---
main:
CALL init_gpu_driver
LUI R0, 65312
ORI R0, 8224
PUSH R0
POP R0
CALL gpu_clear
LDI R0, 50
PUSH R0
LDI R0, 50
PUSH R0
LDI R0, 200
PUSH R0
LDI R0, 100
PUSH R0
LUI R0, 65472
ORI R0, 49344
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
LDI R0, 52
PUSH R0
LDI R0, 52
PUSH R0
LDI R0, 196
PUSH R0
LDI R0, 18
PUSH R0
LUI R0, 65280
ORI R0, 128
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
LDI R0, 120
PUSH R0
LDI R0, 90
PUSH R0
LDI R0, 76
PUSH R0
LUI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R0, 128
PUSH R0
LDI R0, 90
PUSH R0
LDI R0, 79
PUSH R0
LUI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R0, 136
PUSH R0
LDI R0, 90
PUSH R0
LDI R0, 82
PUSH R0
LUI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R0, 144
PUSH R0
LDI R0, 90
PUSH R0
LDI R0, 65
PUSH R0
LUI R0, 65280
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
while_2:
LDI R0, 1
CMPI R0, 0
JZ endwhile_3
JMP while_2
endwhile_3:
exit_main_1:
RET
; --- Function: init_gpu_driver ---
init_gpu_driver:
LDI R0, 1024
MOV R1, R0
LD R0, R1
LDI R1, v_base_2
ST R1, R0
LUI R0, 7
ORI R0, 59648
LDI R1, v_offset_3
ST R1, R0
LDI R2, v_base_2
LD R0, R2
LDI R2, v_offset_3
LD R1, R2
ADD R0, R1
LDI R1, g_gpu_regs_ptr_1
ST R1, R0
exit_init_gpu_driver_4:
RET
; --- Function: gpu_clear ---
gpu_clear:
LDI R12, arg_gpu_clear_color_5
ST R12, R0
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_4
ST R1, R0
LDI R2, arg_gpu_clear_color_5
LD R0, R2
PUSH R0
LDI R2, v_regs_4
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_regs_4
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_clear_5:
RET
; --- Function: gpu_rect ---
gpu_rect:
LDI R12, arg_gpu_rect_x_6
ST R12, R0
LDI R12, arg_gpu_rect_y_6
ST R12, R1
LDI R12, arg_gpu_rect_w_6
ST R12, R2
LDI R12, arg_gpu_rect_h_6
ST R12, R3
LDI R12, arg_gpu_rect_color_6
ST R12, R4
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_5
ST R1, R0
LDI R2, arg_gpu_rect_x_6
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_y_6
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_w_6
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_h_6
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 20
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_color_6
LD R0, R2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 2
PUSH R0
LDI R2, v_regs_5
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_rect_6:
RET
; --- Function: gpu_char ---
gpu_char:
LDI R12, arg_gpu_char_x_7
ST R12, R0
LDI R12, arg_gpu_char_y_7
ST R12, R1
LDI R12, arg_gpu_char_code_7
ST R12, R2
LDI R12, arg_gpu_char_color_7
ST R12, R3
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_6
ST R1, R0
LDI R2, arg_gpu_char_x_7
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_y_7
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_code_7
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_color_7
LD R0, R2
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 3
PUSH R0
LDI R2, v_regs_6
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_char_7:
RET
g_gpu_regs_ptr_1:
.data 0
v_base_2:
.data 0
v_offset_3:
.data 0
arg_gpu_clear_color_5:
.data 0
v_regs_4:
.data 0
arg_gpu_rect_x_6:
.data 0
arg_gpu_rect_y_6:
.data 0
arg_gpu_rect_w_6:
.data 0
arg_gpu_rect_h_6:
.data 0
arg_gpu_rect_color_6:
.data 0
v_regs_5:
.data 0
arg_gpu_char_x_7:
.data 0
arg_gpu_char_y_7:
.data 0
arg_gpu_char_code_7:
.data 0
arg_gpu_char_color_7:
.data 0
v_regs_6:
.data 0
