; Generated by LoraCompiler v3.1 (Strings & Imports)
JMP main
; --- Function: init_gpu_driver ---
init_gpu_driver:
LDI R0, 1024
MOV R1, R0
LD R0, R1
LDI R1, v_base_7
ST R1, R0
LDI R0, 1040
MOV R1, R0
LD R0, R1
LDI R1, v_size_8
ST R1, R0
LDI R2, v_size_8
LD R0, R2
LDI R1, 64
SUB R0, R1
LDI R1, v_offset_9
ST R1, R0
LDI R2, v_base_7
LD R0, R2
LDI R2, v_offset_9
LD R1, R2
ADD R0, R1
LDI R1, g_gpu_regs_ptr_1
ST R1, R0
exit_init_gpu_driver_1:
RET
; --- Function: gpu_clear ---
gpu_clear:
LDI R12, arg_gpu_clear_color_2
ST R12, R0
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_10
ST R1, R0
LDI R2, arg_gpu_clear_color_2
LD R0, R2
PUSH R0
LDI R2, v_regs_10
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_regs_10
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_clear_2:
RET
; --- Function: gpu_rect ---
gpu_rect:
LDI R12, arg_gpu_rect_x_3
ST R12, R0
LDI R12, arg_gpu_rect_y_3
ST R12, R1
LDI R12, arg_gpu_rect_w_3
ST R12, R2
LDI R12, arg_gpu_rect_h_3
ST R12, R3
LDI R12, arg_gpu_rect_color_3
ST R12, R4
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_11
ST R1, R0
LDI R2, arg_gpu_rect_x_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_y_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_w_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_h_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 20
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_color_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_rect_3:
RET
; --- Function: gpu_char ---
gpu_char:
LDI R12, arg_gpu_char_x_4
ST R12, R0
LDI R12, arg_gpu_char_y_4
ST R12, R1
LDI R12, arg_gpu_char_code_4
ST R12, R2
LDI R12, arg_gpu_char_color_4
ST R12, R3
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_12
ST R1, R0
LDI R2, arg_gpu_char_x_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_y_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_code_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_color_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 3
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_char_4:
RET
; --- Function: gpu_print ---
gpu_print:
LDI R12, arg_gpu_print_x_5
ST R12, R0
LDI R12, arg_gpu_print_y_5
ST R12, R1
LDI R12, arg_gpu_print_str_ptr_5
ST R12, R2
LDI R12, arg_gpu_print_color_5
ST R12, R3
LDI R2, arg_gpu_print_str_ptr_5
LD R0, R2
LDI R1, v_ptr_13
ST R1, R0
LDI R2, arg_gpu_print_x_5
LD R0, R2
LDI R1, v_cx_14
ST R1, R0
while_6:
LDI R0, 1
CMPI R0, 0
JZ endwhile_7
LDI R2, v_ptr_13
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_char_15
ST R1, R0
LDI R2, v_char_15
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_8
JMP endwhile_7
JMP endif_9
else_8:
endif_9:
LDI R2, v_cx_14
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_y_5
LD R0, R2
PUSH R0
LDI R2, v_char_15
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_color_5
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_14
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_14
ST R1, R0
LDI R2, v_ptr_13
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, v_ptr_13
ST R1, R0
JMP while_6
endwhile_7:
exit_gpu_print_5:
RET
; --- Function: gpu_print_hex ---
gpu_print_hex:
LDI R12, arg_gpu_print_hex_x_10
ST R12, R0
LDI R12, arg_gpu_print_hex_y_10
ST R12, R1
LDI R12, arg_gpu_print_hex_val_10
ST R12, R2
LDI R12, arg_gpu_print_hex_color_10
ST R12, R3
LDI R0, 28
LDI R1, v_i_16
ST R1, R0
LDI R2, arg_gpu_print_hex_x_10
LD R0, R2
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 48
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 120
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
while_11:
LDI R2, v_i_16
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL endwhile_12
LDI R2, arg_gpu_print_hex_val_10
LD R0, R2
LDI R2, v_i_16
LD R1, R2
SHR R0, R1
LDI R1, 15
AND R0, R1
LDI R1, v_digit_18
ST R1, R0
LDI R0, 0
LDI R1, v_char_19
ST R1, R0
LDI R2, v_digit_18
LD R0, R2
PUSH R0
LDI R0, 10
MOV R1, R0
POP R0
CMP R0, R1
JG else_13
JZ else_13
LDI R0, 48
LDI R2, v_digit_18
LD R1, R2
ADD R0, R1
LDI R1, v_char_19
ST R1, R0
JMP endif_14
else_13:
LDI R0, 55
LDI R2, v_digit_18
LD R1, R2
ADD R0, R1
LDI R1, v_char_19
ST R1, R0
endif_14:
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R2, v_char_19
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_i_16
LD R0, R2
LDI R1, 4
SUB R0, R1
LDI R1, v_i_16
ST R1, R0
JMP while_11
endwhile_12:
exit_gpu_print_hex_10:
RET
; --- Function: init_keyboard_driver ---
init_keyboard_driver:
LDI R0, 1032
MOV R1, R0
LD R0, R1
LDI R1, g_keyboard_regs_ptr_3
ST R1, R0
exit_init_keyboard_driver_15:
RET
; --- Function: poll_keyboard ---
poll_keyboard:
LDI R2, g_keyboard_regs_ptr_3
LD R0, R2
LDI R1, v_base_20
ST R1, R0
LDI R2, v_base_20
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_17
LDI R0, 0
JMP exit_poll_keyboard_16
JMP endif_18
else_17:
endif_18:
LDI R2, v_base_20
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_count_21
ST R1, R0
LDI R2, v_count_21
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL else_19
JZ else_19
LDI R2, v_base_20
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_key_22
ST R1, R0
LDI R2, v_key_22
LD R0, R2
JMP exit_poll_keyboard_16
JMP endif_20
else_19:
endif_20:
LDI R0, 0
JMP exit_poll_keyboard_16
exit_poll_keyboard_16:
RET
; --- Function: init_hardware ---
init_hardware:
CALL init_gpu_driver
CALL init_keyboard_driver
LDI R0, 1028
MOV R1, R0
LD R0, R1
LDI R1, g_disk_regs_ptr_2
ST R1, R0
LDI R0, 6
PUSH R0
POP R0
CALL find_device
LDI R1, v_world_base_23
ST R1, R0
LDI R2, v_world_base_23
LD R0, R2
LDI R1, g_world_regs_ptr_4
ST R1, R0
exit_init_hardware_21:
RET
; --- Function: hardware_count ---
hardware_count:
LUI R0, 255
ORI R0, 61440
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 19535
ORI R0, 21057
MOV R1, R0
POP R0
CMP R0, R1
JZ else_23
LDI R0, 0
JMP exit_hardware_count_22
JMP endif_24
else_23:
endif_24:
LUI R0, 255
ORI R0, 61440
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
JMP exit_hardware_count_22
exit_hardware_count_22:
RET
; --- Function: find_device ---
find_device:
LDI R12, arg_find_device_device_type_25
ST R12, R0
LUI R0, 255
ORI R0, 61440
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 19535
ORI R0, 21057
MOV R1, R0
POP R0
CMP R0, R1
JZ else_26
LDI R0, 0
JMP exit_find_device_25
JMP endif_27
else_26:
endif_27:
LUI R0, 255
ORI R0, 61440
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_count_24
ST R1, R0
LDI R0, 0
LDI R1, v_index_25
ST R1, R0
while_28:
LDI R2, v_index_25
LD R0, R2
PUSH R0
LDI R2, v_count_24
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_29
JZ endwhile_29
LUI R0, 255
ORI R0, 61440
LDI R1, 8
ADD R0, R1
LDI R1, v_entry_26
ST R1, R0
LDI R2, v_entry_26
LD R0, R2
MOV R1, R0
LD R0, R1
PUSH R0
LDI R2, arg_find_device_device_type_25
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_30
LDI R2, v_entry_26
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
JMP exit_find_device_25
JMP endif_31
else_30:
endif_31:
LDI R2, v_index_25
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_index_25
ST R1, R0
JMP while_28
endwhile_29:
LDI R0, 0
JMP exit_find_device_25
exit_find_device_25:
RET
; --- Function: string_equals ---
string_equals:
LDI R12, arg_string_equals_left_32
ST R12, R0
LDI R12, arg_string_equals_right_32
ST R12, R1
LDI R2, arg_string_equals_left_32
LD R0, R2
LDI R1, v_a_27
ST R1, R0
LDI R2, arg_string_equals_right_32
LD R0, R2
LDI R1, v_b_28
ST R1, R0
while_33:
LDI R0, 1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ endwhile_34
LDI R2, v_a_27
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_ca_29
ST R1, R0
LDI R2, v_b_28
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_cb_30
ST R1, R0
LDI R2, v_ca_29
LD R0, R2
PUSH R0
LDI R2, v_cb_30
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JZ else_35
LDI R0, 0
JMP exit_string_equals_32
JMP endif_36
else_35:
endif_36:
LDI R2, v_ca_29
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_37
LDI R0, 1
JMP exit_string_equals_32
JMP endif_38
else_37:
endif_38:
LDI R2, v_a_27
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, v_a_27
ST R1, R0
LDI R2, v_b_28
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, v_b_28
ST R1, R0
JMP while_33
endwhile_34:
exit_string_equals_32:
RET
; --- Function: string_clear ---
string_clear:
LDI R12, arg_string_clear_buffer_39
ST R12, R0
LDI R12, arg_string_clear_capacity_39
ST R12, R1
LDI R0, 0
LDI R1, v_index_31
ST R1, R0
while_40:
LDI R2, v_index_31
LD R0, R2
PUSH R0
LDI R2, arg_string_clear_capacity_39
LD R0, R2
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_41
JZ endwhile_41
LDI R0, 0
PUSH R0
LDI R2, arg_string_clear_buffer_39
LD R0, R2
PUSH R0
LDI R2, v_index_31
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_index_31
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_index_31
ST R1, R0
JMP while_40
endwhile_41:
exit_string_clear_39:
RET
; --- Function: disk_transfer ---
disk_transfer:
LDI R12, arg_disk_transfer_command_42
ST R12, R0
LDI R12, arg_disk_transfer_lba_42
ST R12, R1
LDI R12, arg_disk_transfer_count_42
ST R12, R2
LDI R12, arg_disk_transfer_dma_address_42
ST R12, R3
LDI R2, g_disk_regs_ptr_2
LD R0, R2
LDI R1, v_base_32
ST R1, R0
LDI R2, v_base_32
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_43
LDI R0, 1
JMP exit_disk_transfer_42
JMP endif_44
else_43:
endif_44:
LDI R2, arg_disk_transfer_lba_42
LD R0, R2
PUSH R0
LDI R2, v_base_32
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_disk_transfer_count_42
LD R0, R2
PUSH R0
LDI R2, v_base_32
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_disk_transfer_dma_address_42
LD R0, R2
PUSH R0
LDI R2, v_base_32
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_disk_transfer_command_42
LD R0, R2
PUSH R0
LDI R2, v_base_32
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
while_45:
LDI R2, v_base_32
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ endwhile_46
WAIT 10
JMP while_45
endwhile_46:
LDI R2, v_base_32
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
JMP exit_disk_transfer_42
exit_disk_transfer_42:
RET
; --- Function: disk_read ---
disk_read:
LDI R12, arg_disk_read_lba_47
ST R12, R0
LDI R12, arg_disk_read_count_47
ST R12, R1
LDI R12, arg_disk_read_dma_address_47
ST R12, R2
LDI R0, 1
PUSH R0
LDI R2, arg_disk_read_lba_47
LD R0, R2
PUSH R0
LDI R2, arg_disk_read_count_47
LD R0, R2
PUSH R0
LDI R2, arg_disk_read_dma_address_47
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL disk_transfer
JMP exit_disk_read_47
exit_disk_read_47:
RET
; --- Function: disk_write ---
disk_write:
LDI R12, arg_disk_write_lba_48
ST R12, R0
LDI R12, arg_disk_write_count_48
ST R12, R1
LDI R12, arg_disk_write_dma_address_48
ST R12, R2
LDI R0, 2
PUSH R0
LDI R2, arg_disk_write_lba_48
LD R0, R2
PUSH R0
LDI R2, arg_disk_write_count_48
LD R0, R2
PUSH R0
LDI R2, arg_disk_write_dma_address_48
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL disk_transfer
JMP exit_disk_write_48
exit_disk_write_48:
RET
; --- Function: fs_init ---
fs_init:
LDI R0, 64
PUSH R0
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
PUSH R0
POP R2
POP R1
POP R0
CALL disk_read
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_50
LDI R0, 0
JMP exit_fs_init_49
JMP endif_51
else_50:
endif_51:
LUI R0, 1
ORI R0, 32768
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 12627
ORI R0, 17996
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_52
LDI R0, 1
JMP exit_fs_init_49
JMP endif_53
else_52:
endif_53:
LDI R0, 0
LDI R1, v_index_33
ST R1, R0
while_54:
LDI R2, v_index_33
LD R0, R2
PUSH R0
LDI R0, 128
MOV R1, R0
POP R0
CMP R0, R1
JG endwhile_55
JZ endwhile_55
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 32768
PUSH R0
LDI R2, v_index_33
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_index_33
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_index_33
ST R1, R0
JMP while_54
endwhile_55:
LUI R0, 12627
ORI R0, 17996
PUSH R0
LUI R0, 1
ORI R0, 32768
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 110
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 32
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 111
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 36
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 116
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 40
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 101
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 44
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 48
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 64
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 65
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 68
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 72
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 4
PUSH R0
LUI R0, 1
ORI R0, 32768
LDI R1, 76
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 64
PUSH R0
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
PUSH R0
POP R2
POP R1
POP R0
CALL disk_write
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_56
LDI R0, 0
JMP exit_fs_init_49
JMP endif_57
else_56:
endif_57:
LDI R0, 1
JMP exit_fs_init_49
exit_fs_init_49:
RET
; --- Function: fs_write_note ---
fs_write_note:
LDI R12, arg_fs_write_note_buffer_58
ST R12, R0
LDI R12, arg_fs_write_note_length_58
ST R12, R1
LDI R2, arg_fs_write_note_length_58
LD R0, R2
PUSH R0
LDI R0, 511
MOV R1, R0
POP R0
CMP R0, R1
JL else_59
JZ else_59
LDI R0, 0
JMP exit_fs_write_note_58
JMP endif_60
else_59:
endif_60:
LDI R0, 0
PUSH R0
LDI R2, arg_fs_write_note_buffer_58
LD R0, R2
PUSH R0
LDI R2, arg_fs_write_note_length_58
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 65
PUSH R0
LDI R0, 4
PUSH R0
LDI R2, arg_fs_write_note_buffer_58
LD R0, R2
PUSH R0
POP R2
POP R1
POP R0
CALL disk_write
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_61
LDI R0, 0
JMP exit_fs_write_note_58
JMP endif_62
else_61:
endif_62:
LDI R2, arg_fs_write_note_length_58
LD R0, R2
PUSH R0
LUI R0, 1
ORI R0, 32840
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 64
PUSH R0
LDI R0, 1
PUSH R0
LUI R0, 1
ORI R0, 32768
PUSH R0
POP R2
POP R1
POP R0
CALL disk_write
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_63
LDI R0, 0
JMP exit_fs_write_note_58
JMP endif_64
else_63:
endif_64:
LDI R0, 1
JMP exit_fs_write_note_58
exit_fs_write_note_58:
RET
; --- Function: fs_read_note ---
fs_read_note:
LDI R0, 65
PUSH R0
LDI R0, 4
PUSH R0
LUI R0, 1
ORI R0, 33280
PUSH R0
POP R2
POP R1
POP R0
CALL disk_read
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_66
LDI R0, 0
JMP exit_fs_read_note_65
JMP endif_67
else_66:
endif_67:
LUI R0, 1
ORI R0, 32840
MOV R1, R0
LD R0, R1
LDI R1, v_length_34
ST R1, R0
LDI R2, v_length_34
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JG else_68
JZ else_68
LDI R0, 0
JMP exit_fs_read_note_65
JMP endif_69
else_68:
endif_69:
LDI R2, v_length_34
LD R0, R2
PUSH R0
LDI R0, 511
MOV R1, R0
POP R0
CMP R0, R1
JL else_70
JZ else_70
LDI R0, 0
JMP exit_fs_read_note_65
JMP endif_71
else_70:
endif_71:
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 33280
PUSH R0
LDI R2, v_length_34
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LUI R0, 1
ORI R0, 33280
JMP exit_fs_read_note_65
exit_fs_read_note_65:
RET
; --- Function: fs_note_length ---
fs_note_length:
LUI R0, 1
ORI R0, 32840
MOV R1, R0
LD R0, R1
JMP exit_fs_note_length_72
exit_fs_note_length_72:
RET
; --- Function: terminal_reset ---
terminal_reset:
LUI R0, 65312
ORI R0, 8224
PUSH R0
POP R0
CALL gpu_clear
LDI R0, 0
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, 480
PUSH R0
LDI R0, 16
PUSH R0
LUI R0, 65280
ORI R0, 128
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
LDI R0, 8
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, str_1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 10
LDI R1, g_term_cursor_x_5
ST R1, R0
LDI R0, 32
LDI R1, g_term_cursor_y_6
ST R1, R0
exit_terminal_reset_73:
RET
; --- Function: terminal_newline ---
terminal_newline:
LDI R0, 10
LDI R1, g_term_cursor_x_5
ST R1, R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
ADD R0, R1
LDI R1, g_term_cursor_y_6
ST R1, R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R0, 240
MOV R1, R0
POP R0
CMP R0, R1
JL else_75
JZ else_75
CALL terminal_reset
JMP endif_76
else_75:
endif_76:
exit_terminal_newline_74:
RET
; --- Function: terminal_line ---
terminal_line:
LDI R12, arg_terminal_line_text_77
ST R12, R0
LDI R12, arg_terminal_line_color_77
ST R12, R1
LDI R0, 10
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R2, arg_terminal_line_text_77
LD R0, R2
PUSH R0
LDI R2, arg_terminal_line_color_77
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
CALL terminal_newline
exit_terminal_line_77:
RET
; --- Function: shell_prompt ---
shell_prompt:
LDI R0, 10
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R0, str_2
PUSH R0
LUI R0, 65365
ORI R0, 65365
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 58
LDI R1, g_term_cursor_x_5
ST R1, R0
exit_shell_prompt_78:
RET
; --- Function: shell_help ---
shell_help:
LDI R0, str_3
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_4
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_5
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_6
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_7
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_8
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_9
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_10
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
exit_shell_help_79:
RET
; --- Function: shell_write_note ---
shell_write_note:
LDI R0, str_11
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 0
LDI R1, v_length_35
ST R1, R0
LUI R0, 1
ORI R0, 33280
PUSH R0
LDI R0, 511
LDI R1, 1
ADD R0, R1
PUSH R0
POP R1
POP R0
CALL string_clear
LDI R0, 10
LDI R1, g_term_cursor_x_5
ST R1, R0
while_81:
LDI R0, 1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ endwhile_82
CALL poll_keyboard
LDI R1, v_key_36
ST R1, R0
LDI R2, v_key_36
LD R0, R2
PUSH R0
LDI R0, 13
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_83
CALL terminal_newline
LUI R0, 1
ORI R0, 33280
PUSH R0
LDI R2, v_length_35
LD R0, R2
PUSH R0
POP R1
POP R0
CALL fs_write_note
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_85
LDI R0, str_12
PUSH R0
LUI R0, 65365
ORI R0, 65365
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP endif_86
else_85:
LDI R0, str_13
PUSH R0
LDI R0, -32640
PUSH R0
POP R1
POP R0
CALL terminal_line
endif_86:
JMP exit_shell_write_note_80
JMP endif_84
else_83:
LDI R2, v_key_36
LD R0, R2
PUSH R0
LDI R0, 8
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_87
LDI R2, v_length_35
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL else_89
JZ else_89
LDI R2, v_length_35
LD R0, R2
LDI R1, 1
SUB R0, R1
LDI R1, v_length_35
ST R1, R0
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 33280
PUSH R0
LDI R2, v_length_35
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, g_term_cursor_x_5
LD R0, R2
LDI R1, 8
SUB R0, R1
LDI R1, g_term_cursor_x_5
ST R1, R0
LDI R2, g_term_cursor_x_5
LD R0, R2
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R0, 8
PUSH R0
LDI R0, 16
PUSH R0
LUI R0, 65312
ORI R0, 8224
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
JMP endif_90
else_89:
endif_90:
JMP endif_88
else_87:
LDI R2, v_key_36
LD R0, R2
PUSH R0
LDI R0, 32
MOV R1, R0
POP R0
CMP R0, R1
JL else_91
LDI R2, v_length_35
LD R0, R2
PUSH R0
LDI R0, 48
MOV R1, R0
POP R0
CMP R0, R1
JG else_93
JZ else_93
LDI R2, v_key_36
LD R0, R2
PUSH R0
LUI R0, 1
ORI R0, 33280
PUSH R0
LDI R2, v_length_35
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_length_35
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_length_35
ST R1, R0
LDI R2, g_term_cursor_x_5
LD R0, R2
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R2, v_key_36
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, g_term_cursor_x_5
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, g_term_cursor_x_5
ST R1, R0
JMP endif_94
else_93:
endif_94:
JMP endif_92
else_91:
endif_92:
endif_88:
endif_84:
WAIT 10
JMP while_81
endwhile_82:
exit_shell_write_note_80:
RET
; --- Function: shell_hardware ---
shell_hardware:
LDI R0, str_14
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 120
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R0, str_15
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 168
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
CALL hardware_count
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, str_16
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 58
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R0, 1024
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, str_17
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 58
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, g_disk_regs_ptr_2
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, str_18
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 90
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, g_keyboard_regs_ptr_3
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, str_19
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 66
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, g_world_regs_ptr_4
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
exit_shell_hardware_95:
RET
; --- Function: shell_world ---
shell_world:
LDI R2, g_world_regs_ptr_4
LD R0, R2
LDI R1, v_base_37
ST R1, R0
LDI R2, v_base_37
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_97
LDI R0, str_20
PUSH R0
LDI R0, -32640
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP exit_shell_world_96
JMP endif_98
else_97:
endif_98:
LDI R0, str_21
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 122
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_base_37
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, 218
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_base_37
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, 314
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_base_37
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R2, v_base_37
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_99
LDI R0, str_22
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 138
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_base_37
LD R0, R2
LDI R1, 28
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
LDI R0, str_23
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, 138
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
LDI R1, 16
SUB R0, R1
PUSH R0
LDI R2, v_base_37
LD R0, R2
LDI R1, 32
ADD R0, R1
MOV R1, R0
LD R0, R1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print_hex
JMP endif_100
else_99:
LDI R0, str_24
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
endif_100:
exit_shell_world_96:
RET
; --- Function: shell_execute ---
shell_execute:
LDI R12, arg_shell_execute_command_101
ST R12, R0
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_25
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_102
JMP exit_shell_execute_101
JMP endif_103
else_102:
endif_103:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_26
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_104
CALL shell_help
JMP exit_shell_execute_101
JMP endif_105
else_104:
endif_105:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_27
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_106
LDI R0, str_28
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
LDI R0, str_29
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP exit_shell_execute_101
JMP endif_107
else_106:
endif_107:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_30
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_108
CALL shell_hardware
JMP exit_shell_execute_101
JMP endif_109
else_108:
endif_109:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_31
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_110
CALL terminal_reset
JMP exit_shell_execute_101
JMP endif_111
else_110:
endif_111:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_32
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_112
LDI R0, str_33
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP exit_shell_execute_101
JMP endif_113
else_112:
endif_113:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_34
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_114
CALL fs_read_note
LDI R1, v_note_38
ST R1, R0
LDI R2, v_note_38
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_116
LDI R0, str_35
PUSH R0
LDI R0, -32640
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP endif_117
else_116:
CALL fs_note_length
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_118
LDI R0, str_36
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP endif_119
else_118:
LDI R2, v_note_38
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R1
POP R0
CALL terminal_line
endif_119:
endif_117:
JMP exit_shell_execute_101
JMP endif_115
else_114:
endif_115:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_37
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_120
CALL shell_write_note
JMP exit_shell_execute_101
JMP endif_121
else_120:
endif_121:
LDI R2, arg_shell_execute_command_101
LD R0, R2
PUSH R0
LDI R0, str_38
PUSH R0
POP R1
POP R0
CALL string_equals
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_122
CALL shell_world
JMP exit_shell_execute_101
JMP endif_123
else_122:
endif_123:
LDI R0, str_39
PUSH R0
LDI R0, -32640
PUSH R0
POP R1
POP R0
CALL terminal_line
exit_shell_execute_101:
RET
; --- Function: shell_run ---
shell_run:
LDI R0, 0
LDI R1, v_length_39
ST R1, R0
LUI R0, 1
ORI R0, 24576
PUSH R0
LDI R0, 48
PUSH R0
POP R1
POP R0
CALL string_clear
CALL shell_prompt
while_125:
LDI R0, 1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ endwhile_126
CALL poll_keyboard
LDI R1, v_key_40
ST R1, R0
LDI R2, v_key_40
LD R0, R2
PUSH R0
LDI R0, 13
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_127
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 24576
PUSH R0
LDI R2, v_length_39
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
CALL terminal_newline
LUI R0, 1
ORI R0, 24576
PUSH R0
POP R0
CALL shell_execute
LDI R0, 0
LDI R1, v_length_39
ST R1, R0
LUI R0, 1
ORI R0, 24576
PUSH R0
LDI R0, 48
PUSH R0
POP R1
POP R0
CALL string_clear
CALL shell_prompt
JMP endif_128
else_127:
LDI R2, v_key_40
LD R0, R2
PUSH R0
LDI R0, 8
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_129
LDI R2, v_length_39
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL else_131
JZ else_131
LDI R2, v_length_39
LD R0, R2
LDI R1, 1
SUB R0, R1
LDI R1, v_length_39
ST R1, R0
LDI R0, 0
PUSH R0
LUI R0, 1
ORI R0, 24576
PUSH R0
LDI R2, v_length_39
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, g_term_cursor_x_5
LD R0, R2
LDI R1, 8
SUB R0, R1
LDI R1, g_term_cursor_x_5
ST R1, R0
LDI R2, g_term_cursor_x_5
LD R0, R2
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R0, 8
PUSH R0
LDI R0, 16
PUSH R0
LUI R0, 65312
ORI R0, 8224
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
JMP endif_132
else_131:
endif_132:
JMP endif_130
else_129:
LDI R2, v_key_40
LD R0, R2
PUSH R0
LDI R0, 32
MOV R1, R0
POP R0
CMP R0, R1
JL else_133
LDI R2, v_length_39
LD R0, R2
PUSH R0
LDI R0, 48
LDI R1, 1
SUB R0, R1
MOV R1, R0
POP R0
CMP R0, R1
JG else_135
JZ else_135
LDI R2, v_key_40
LD R0, R2
PUSH R0
LUI R0, 1
ORI R0, 24576
PUSH R0
LDI R2, v_length_39
LD R0, R2
LDI R1, 4
MUL R0, R1
MOV R1, R0
POP R0
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, v_length_39
LD R0, R2
LDI R1, 1
ADD R0, R1
LDI R1, v_length_39
ST R1, R0
LDI R2, g_term_cursor_x_5
LD R0, R2
PUSH R0
LDI R2, g_term_cursor_y_6
LD R0, R2
PUSH R0
LDI R2, v_key_40
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, g_term_cursor_x_5
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, g_term_cursor_x_5
ST R1, R0
JMP endif_136
else_135:
endif_136:
JMP endif_134
else_133:
endif_134:
endif_130:
endif_128:
WAIT 10
JMP while_125
endwhile_126:
exit_shell_run_124:
RET
; --- Function: main ---
main:
CALL init_hardware
CALL terminal_reset
LDI R0, str_40
PUSH R0
LUI R0, 65365
ORI R0, 65365
PUSH R0
POP R1
POP R0
CALL terminal_line
CALL fs_init
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_138
LDI R0, str_41
PUSH R0
LUI R0, 65365
ORI R0, 65365
PUSH R0
POP R1
POP R0
CALL terminal_line
JMP endif_139
else_138:
LDI R0, str_42
PUSH R0
LDI R0, -32640
PUSH R0
POP R1
POP R0
CALL terminal_line
endif_139:
LDI R0, str_43
PUSH R0
LUI R0, 65456
ORI R0, 45232
PUSH R0
POP R1
POP R0
CALL terminal_line
CALL shell_run
exit_main_137:
RET
g_gpu_regs_ptr_1:
.data 0
g_disk_regs_ptr_2:
.data 0
g_keyboard_regs_ptr_3:
.data 0
g_world_regs_ptr_4:
.data 0
g_term_cursor_x_5:
.data 10
g_term_cursor_y_6:
.data 40
v_base_7:
.data 0
v_size_8:
.data 0
v_offset_9:
.data 0
arg_gpu_clear_color_2:
.data 0
v_regs_10:
.data 0
arg_gpu_rect_x_3:
.data 0
arg_gpu_rect_y_3:
.data 0
arg_gpu_rect_w_3:
.data 0
arg_gpu_rect_h_3:
.data 0
arg_gpu_rect_color_3:
.data 0
v_regs_11:
.data 0
arg_gpu_char_x_4:
.data 0
arg_gpu_char_y_4:
.data 0
arg_gpu_char_code_4:
.data 0
arg_gpu_char_color_4:
.data 0
v_regs_12:
.data 0
arg_gpu_print_x_5:
.data 0
arg_gpu_print_y_5:
.data 0
arg_gpu_print_str_ptr_5:
.data 0
arg_gpu_print_color_5:
.data 0
v_ptr_13:
.data 0
v_cx_14:
.data 0
v_char_15:
.data 0
arg_gpu_print_hex_x_10:
.data 0
arg_gpu_print_hex_y_10:
.data 0
arg_gpu_print_hex_val_10:
.data 0
arg_gpu_print_hex_color_10:
.data 0
v_i_16:
.data 0
v_cx_17:
.data 0
v_digit_18:
.data 0
v_char_19:
.data 0
v_base_20:
.data 0
v_count_21:
.data 0
v_key_22:
.data 0
v_world_base_23:
.data 0
arg_find_device_device_type_25:
.data 0
v_count_24:
.data 0
v_index_25:
.data 0
v_entry_26:
.data 0
arg_string_equals_left_32:
.data 0
arg_string_equals_right_32:
.data 0
v_a_27:
.data 0
v_b_28:
.data 0
v_ca_29:
.data 0
v_cb_30:
.data 0
arg_string_clear_buffer_39:
.data 0
arg_string_clear_capacity_39:
.data 0
v_index_31:
.data 0
arg_disk_transfer_command_42:
.data 0
arg_disk_transfer_lba_42:
.data 0
arg_disk_transfer_count_42:
.data 0
arg_disk_transfer_dma_address_42:
.data 0
v_base_32:
.data 0
arg_disk_read_lba_47:
.data 0
arg_disk_read_count_47:
.data 0
arg_disk_read_dma_address_47:
.data 0
arg_disk_write_lba_48:
.data 0
arg_disk_write_count_48:
.data 0
arg_disk_write_dma_address_48:
.data 0
v_index_33:
.data 0
arg_fs_write_note_buffer_58:
.data 0
arg_fs_write_note_length_58:
.data 0
v_length_34:
.data 0
str_1:
.data 76
.data 111
.data 114
.data 97
.data 79
.data 83
.data 32
.data 50
.data 46
.data 48
.data 0
arg_terminal_line_text_77:
.data 0
arg_terminal_line_color_77:
.data 0
str_2:
.data 108
.data 111
.data 114
.data 97
.data 62
.data 32
.data 0
str_3:
.data 104
.data 101
.data 108
.data 112
.data 32
.data 32
.data 45
.data 32
.data 108
.data 105
.data 115
.data 116
.data 32
.data 99
.data 111
.data 109
.data 109
.data 97
.data 110
.data 100
.data 115
.data 0
str_4:
.data 97
.data 98
.data 111
.data 117
.data 116
.data 32
.data 45
.data 32
.data 115
.data 121
.data 115
.data 116
.data 101
.data 109
.data 32
.data 118
.data 101
.data 114
.data 115
.data 105
.data 111
.data 110
.data 0
str_5:
.data 104
.data 119
.data 32
.data 32
.data 32
.data 32
.data 45
.data 32
.data 100
.data 105
.data 115
.data 99
.data 111
.data 118
.data 101
.data 114
.data 101
.data 100
.data 32
.data 104
.data 97
.data 114
.data 100
.data 119
.data 97
.data 114
.data 101
.data 0
str_6:
.data 99
.data 108
.data 101
.data 97
.data 114
.data 32
.data 45
.data 32
.data 99
.data 108
.data 101
.data 97
.data 114
.data 32
.data 116
.data 101
.data 114
.data 109
.data 105
.data 110
.data 97
.data 108
.data 0
str_7:
.data 108
.data 115
.data 32
.data 32
.data 32
.data 32
.data 45
.data 32
.data 108
.data 105
.data 115
.data 116
.data 32
.data 102
.data 105
.data 108
.data 101
.data 115
.data 0
str_8:
.data 99
.data 97
.data 116
.data 32
.data 110
.data 111
.data 116
.data 101
.data 32
.data 45
.data 32
.data 114
.data 101
.data 97
.data 100
.data 32
.data 110
.data 111
.data 116
.data 101
.data 0
str_9:
.data 119
.data 114
.data 105
.data 116
.data 101
.data 32
.data 110
.data 111
.data 116
.data 101
.data 32
.data 45
.data 32
.data 114
.data 101
.data 112
.data 108
.data 97
.data 99
.data 101
.data 32
.data 110
.data 111
.data 116
.data 101
.data 0
str_10:
.data 119
.data 111
.data 114
.data 108
.data 100
.data 32
.data 45
.data 32
.data 105
.data 110
.data 115
.data 112
.data 101
.data 99
.data 116
.data 32
.data 112
.data 108
.data 97
.data 121
.data 101
.data 114
.data 47
.data 116
.data 97
.data 114
.data 103
.data 101
.data 116
.data 0
str_11:
.data 69
.data 110
.data 116
.data 101
.data 114
.data 32
.data 110
.data 111
.data 116
.data 101
.data 32
.data 116
.data 101
.data 120
.data 116
.data 58
.data 0
v_length_35:
.data 0
v_key_36:
.data 0
str_12:
.data 83
.data 97
.data 118
.data 101
.data 100
.data 32
.data 110
.data 111
.data 116
.data 101
.data 0
str_13:
.data 68
.data 105
.data 115
.data 107
.data 32
.data 119
.data 114
.data 105
.data 116
.data 101
.data 32
.data 102
.data 97
.data 105
.data 108
.data 101
.data 100
.data 0
str_14:
.data 80
.data 110
.data 80
.data 32
.data 100
.data 101
.data 118
.data 105
.data 99
.data 101
.data 115
.data 58
.data 0
str_15:
.data 99
.data 111
.data 117
.data 110
.data 116
.data 0
str_16:
.data 71
.data 80
.data 85
.data 58
.data 0
str_17:
.data 68
.data 105
.data 115
.data 107
.data 58
.data 0
str_18:
.data 75
.data 101
.data 121
.data 98
.data 111
.data 97
.data 114
.data 100
.data 58
.data 0
str_19:
.data 87
.data 111
.data 114
.data 108
.data 100
.data 58
.data 0
v_base_37:
.data 0
str_20:
.data 87
.data 111
.data 114
.data 108
.data 100
.data 32
.data 98
.data 114
.data 105
.data 100
.data 103
.data 101
.data 32
.data 117
.data 110
.data 97
.data 118
.data 97
.data 105
.data 108
.data 97
.data 98
.data 108
.data 101
.data 0
str_21:
.data 80
.data 108
.data 97
.data 121
.data 101
.data 114
.data 32
.data 88
.data 47
.data 89
.data 47
.data 90
.data 58
.data 0
str_22:
.data 84
.data 97
.data 114
.data 103
.data 101
.data 116
.data 32
.data 98
.data 108
.data 111
.data 99
.data 107
.data 32
.data 73
.data 68
.data 58
.data 0
str_23:
.data 82
.data 101
.data 100
.data 115
.data 116
.data 111
.data 110
.data 101
.data 32
.data 105
.data 110
.data 112
.data 117
.data 116
.data 58
.data 0
str_24:
.data 78
.data 111
.data 32
.data 98
.data 108
.data 111
.data 99
.data 107
.data 32
.data 105
.data 110
.data 32
.data 114
.data 101
.data 97
.data 99
.data 104
.data 0
arg_shell_execute_command_101:
.data 0
str_25:
.data 0
str_26:
.data 104
.data 101
.data 108
.data 112
.data 0
str_27:
.data 97
.data 98
.data 111
.data 117
.data 116
.data 0
str_28:
.data 76
.data 111
.data 114
.data 97
.data 79
.data 83
.data 32
.data 50
.data 46
.data 48
.data 32
.data 110
.data 97
.data 116
.data 105
.data 118
.data 101
.data 32
.data 115
.data 117
.data 114
.data 118
.data 105
.data 118
.data 97
.data 108
.data 32
.data 79
.data 83
.data 0
str_29:
.data 66
.data 111
.data 111
.data 116
.data 101
.data 100
.data 32
.data 102
.data 114
.data 111
.data 109
.data 32
.data 116
.data 104
.data 101
.data 32
.data 116
.data 97
.data 98
.data 108
.data 101
.data 116
.data 32
.data 100
.data 105
.data 115
.data 107
.data 0
str_30:
.data 104
.data 119
.data 0
str_31:
.data 99
.data 108
.data 101
.data 97
.data 114
.data 0
str_32:
.data 108
.data 115
.data 0
str_33:
.data 110
.data 111
.data 116
.data 101
.data 0
str_34:
.data 99
.data 97
.data 116
.data 32
.data 110
.data 111
.data 116
.data 101
.data 0
v_note_38:
.data 0
str_35:
.data 68
.data 105
.data 115
.data 107
.data 32
.data 114
.data 101
.data 97
.data 100
.data 32
.data 102
.data 97
.data 105
.data 108
.data 101
.data 100
.data 0
str_36:
.data 40
.data 101
.data 109
.data 112
.data 116
.data 121
.data 41
.data 0
str_37:
.data 119
.data 114
.data 105
.data 116
.data 101
.data 32
.data 110
.data 111
.data 116
.data 101
.data 0
str_38:
.data 119
.data 111
.data 114
.data 108
.data 100
.data 0
str_39:
.data 85
.data 110
.data 107
.data 110
.data 111
.data 119
.data 110
.data 32
.data 99
.data 111
.data 109
.data 109
.data 97
.data 110
.data 100
.data 46
.data 32
.data 84
.data 121
.data 112
.data 101
.data 32
.data 104
.data 101
.data 108
.data 112
.data 46
.data 0
v_length_39:
.data 0
v_key_40:
.data 0
str_40:
.data 78
.data 97
.data 116
.data 105
.data 118
.data 101
.data 32
.data 107
.data 101
.data 114
.data 110
.data 101
.data 108
.data 32
.data 114
.data 101
.data 97
.data 100
.data 121
.data 0
str_41:
.data 76
.data 111
.data 114
.data 97
.data 70
.data 83
.data 32
.data 109
.data 111
.data 117
.data 110
.data 116
.data 101
.data 100
.data 0
str_42:
.data 76
.data 111
.data 114
.data 97
.data 70
.data 83
.data 32
.data 117
.data 110
.data 97
.data 118
.data 97
.data 105
.data 108
.data 97
.data 98
.data 108
.data 101
.data 0
str_43:
.data 84
.data 121
.data 112
.data 101
.data 32
.data 104
.data 101
.data 108
.data 112
.data 32
.data 116
.data 111
.data 32
.data 98
.data 101
.data 103
.data 105
.data 110
.data 0
