; Generated by LoraCompiler v3.1 (Strings & Imports)
JMP main
; --- Function: init_gpu_driver ---
init_gpu_driver:
LDI R0, 1024
MOV R1, R0
LD R0, R1
LDI R1, v_base_7
ST R1, R0
LDI R0, 1040
MOV R1, R0
LD R0, R1
LDI R1, v_size_8
ST R1, R0
LDI R2, v_size_8
LD R0, R2
LDI R1, 64
SUB R0, R1
LDI R1, v_offset_9
ST R1, R0
LDI R2, v_base_7
LD R0, R2
LDI R2, v_offset_9
LD R1, R2
ADD R0, R1
LDI R1, g_gpu_regs_ptr_1
ST R1, R0
exit_init_gpu_driver_1:
RET
; --- Function: gpu_clear ---
gpu_clear:
LDI R12, arg_gpu_clear_color_2
ST R12, R0
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_10
ST R1, R0
LDI R2, arg_gpu_clear_color_2
LD R0, R2
PUSH R0
LDI R2, v_regs_10
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 1
PUSH R0
LDI R2, v_regs_10
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_clear_2:
RET
; --- Function: gpu_rect ---
gpu_rect:
LDI R12, arg_gpu_rect_x_3
ST R12, R0
LDI R12, arg_gpu_rect_y_3
ST R12, R1
LDI R12, arg_gpu_rect_w_3
ST R12, R2
LDI R12, arg_gpu_rect_h_3
ST R12, R3
LDI R12, arg_gpu_rect_color_3
ST R12, R4
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_11
ST R1, R0
LDI R2, arg_gpu_rect_x_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_y_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_w_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_h_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 20
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_rect_color_3
LD R0, R2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 2
PUSH R0
LDI R2, v_regs_11
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_rect_3:
RET
; --- Function: gpu_char ---
gpu_char:
LDI R12, arg_gpu_char_x_4
ST R12, R0
LDI R12, arg_gpu_char_y_4
ST R12, R1
LDI R12, arg_gpu_char_code_4
ST R12, R2
LDI R12, arg_gpu_char_color_4
ST R12, R3
LDI R2, g_gpu_regs_ptr_1
LD R0, R2
LDI R1, v_regs_12
ST R1, R0
LDI R2, arg_gpu_char_x_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 8
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_y_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 12
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_code_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 16
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R2, arg_gpu_char_color_4
LD R0, R2
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 24
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
LDI R0, 3
PUSH R0
LDI R2, v_regs_12
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
POP R0
MOV R2, R0
ST R1, R2
exit_gpu_char_4:
RET
; --- Function: gpu_print ---
gpu_print:
LDI R12, arg_gpu_print_x_5
ST R12, R0
LDI R12, arg_gpu_print_y_5
ST R12, R1
LDI R12, arg_gpu_print_str_ptr_5
ST R12, R2
LDI R12, arg_gpu_print_color_5
ST R12, R3
LDI R2, arg_gpu_print_str_ptr_5
LD R0, R2
LDI R1, v_ptr_13
ST R1, R0
LDI R2, arg_gpu_print_x_5
LD R0, R2
LDI R1, v_cx_14
ST R1, R0
while_6:
LDI R0, 1
CMPI R0, 0
JZ endwhile_7
LDI R2, v_ptr_13
LD R0, R2
MOV R1, R0
LD R0, R1
LDI R1, v_char_15
ST R1, R0
LDI R2, v_char_15
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_8
JMP endwhile_7
JMP endif_9
else_8:
endif_9:
LDI R2, v_cx_14
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_y_5
LD R0, R2
PUSH R0
LDI R2, v_char_15
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_color_5
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_14
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_14
ST R1, R0
LDI R2, v_ptr_13
LD R0, R2
LDI R1, 4
ADD R0, R1
LDI R1, v_ptr_13
ST R1, R0
JMP while_6
endwhile_7:
exit_gpu_print_5:
RET
; --- Function: gpu_print_hex ---
gpu_print_hex:
LDI R12, arg_gpu_print_hex_x_10
ST R12, R0
LDI R12, arg_gpu_print_hex_y_10
ST R12, R1
LDI R12, arg_gpu_print_hex_val_10
ST R12, R2
LDI R12, arg_gpu_print_hex_color_10
ST R12, R3
LDI R0, 28
LDI R1, v_i_16
ST R1, R0
LDI R2, arg_gpu_print_hex_x_10
LD R0, R2
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 48
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R0, 120
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
while_11:
LDI R2, v_i_16
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL endwhile_12
LDI R2, arg_gpu_print_hex_val_10
LD R0, R2
LDI R2, v_i_16
LD R1, R2
SHR R0, R1
LDI R1, 15
AND R0, R1
LDI R1, v_digit_18
ST R1, R0
LDI R0, 0
LDI R1, v_char_19
ST R1, R0
LDI R2, v_digit_18
LD R0, R2
PUSH R0
LDI R0, 10
MOV R1, R0
POP R0
CMP R0, R1
JG else_13
JZ else_13
LDI R0, 48
LDI R2, v_digit_18
LD R1, R2
ADD R0, R1
LDI R1, v_char_19
ST R1, R0
JMP endif_14
else_13:
LDI R0, 55
LDI R2, v_digit_18
LD R1, R2
ADD R0, R1
LDI R1, v_char_19
ST R1, R0
endif_14:
LDI R2, v_cx_17
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_y_10
LD R0, R2
PUSH R0
LDI R2, v_char_19
LD R0, R2
PUSH R0
LDI R2, arg_gpu_print_hex_color_10
LD R0, R2
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, v_cx_17
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, v_cx_17
ST R1, R0
LDI R2, v_i_16
LD R0, R2
LDI R1, 4
SUB R0, R1
LDI R1, v_i_16
ST R1, R0
JMP while_11
endwhile_12:
exit_gpu_print_hex_10:
RET
; --- Function: init_keyboard_driver ---
init_keyboard_driver:
LDI R0, 1032
MOV R1, R0
LD R0, R1
LDI R1, g_keyboard_regs_ptr_3
ST R1, R0
exit_init_keyboard_driver_15:
RET
; --- Function: poll_keyboard ---
poll_keyboard:
LDI R2, g_keyboard_regs_ptr_3
LD R0, R2
LDI R1, v_base_20
ST R1, R0
LDI R2, v_base_20
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_17
LDI R0, 0
JMP exit_poll_keyboard_16
JMP endif_18
else_17:
endif_18:
LDI R2, v_base_20
LD R0, R2
LDI R1, 0
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_count_21
ST R1, R0
LDI R2, v_count_21
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JL else_19
JZ else_19
LDI R2, v_base_20
LD R0, R2
LDI R1, 4
ADD R0, R1
MOV R1, R0
LD R0, R1
LDI R1, v_key_22
ST R1, R0
LDI R2, v_key_22
LD R0, R2
JMP exit_poll_keyboard_16
JMP endif_20
else_19:
endif_20:
LDI R0, 0
JMP exit_poll_keyboard_16
exit_poll_keyboard_16:
RET
; --- Function: main ---
main:
CALL init_gpu_driver
LUI R0, 65328
ORI R0, 4112
PUSH R0
POP R0
CALL gpu_clear
LDI R0, 0
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, 480
PUSH R0
LDI R0, 16
PUSH R0
LUI R0, 65408
PUSH R0
POP R4
POP R3
POP R2
POP R1
POP R0
CALL gpu_rect
LDI R0, 8
PUSH R0
LDI R0, 0
PUSH R0
LDI R0, str_1
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 10
PUSH R0
LDI R0, 32
PUSH R0
LDI R0, str_2
PUSH R0
LDI R0, -13184
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 10
PUSH R0
LDI R0, 48
PUSH R0
LDI R0, str_3
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_print
LDI R0, 72
LDI R1, v_cursor_y_23
ST R1, R0
LDI R0, 10
LDI R1, g_term_cursor_x_5
ST R1, R0
while_22:
LDI R0, 1
PUSH R0
LDI R0, 1
MOV R1, R0
POP R0
CMP R0, R1
JNZ endwhile_23
CALL poll_keyboard
LDI R1, v_key_24
ST R1, R0
LDI R2, v_key_24
LD R0, R2
PUSH R0
LDI R0, 0
MOV R1, R0
POP R0
CMP R0, R1
JZ else_24
LDI R2, v_key_24
LD R0, R2
PUSH R0
LDI R0, 13
MOV R1, R0
POP R0
CMP R0, R1
JNZ else_26
LDI R0, 10
LDI R1, g_term_cursor_x_5
ST R1, R0
LDI R2, v_cursor_y_23
LD R0, R2
LDI R1, 16
ADD R0, R1
LDI R1, v_cursor_y_23
ST R1, R0
JMP endif_27
else_26:
LDI R2, g_term_cursor_x_5
LD R0, R2
PUSH R0
LDI R2, v_cursor_y_23
LD R0, R2
PUSH R0
LDI R2, v_key_24
LD R0, R2
PUSH R0
LUI R0, 65535
ORI R0, 65535
PUSH R0
POP R3
POP R2
POP R1
POP R0
CALL gpu_char
LDI R2, g_term_cursor_x_5
LD R0, R2
LDI R1, 8
ADD R0, R1
LDI R1, g_term_cursor_x_5
ST R1, R0
endif_27:
JMP endif_25
else_24:
endif_25:
WAIT 10
JMP while_22
endwhile_23:
exit_main_21:
RET
g_gpu_regs_ptr_1:
.data 0
g_disk_regs_ptr_2:
.data 0
g_keyboard_regs_ptr_3:
.data 0
g_world_regs_ptr_4:
.data 0
g_term_cursor_x_5:
.data 10
g_term_cursor_y_6:
.data 40
v_base_7:
.data 0
v_size_8:
.data 0
v_offset_9:
.data 0
arg_gpu_clear_color_2:
.data 0
v_regs_10:
.data 0
arg_gpu_rect_x_3:
.data 0
arg_gpu_rect_y_3:
.data 0
arg_gpu_rect_w_3:
.data 0
arg_gpu_rect_h_3:
.data 0
arg_gpu_rect_color_3:
.data 0
v_regs_11:
.data 0
arg_gpu_char_x_4:
.data 0
arg_gpu_char_y_4:
.data 0
arg_gpu_char_code_4:
.data 0
arg_gpu_char_color_4:
.data 0
v_regs_12:
.data 0
arg_gpu_print_x_5:
.data 0
arg_gpu_print_y_5:
.data 0
arg_gpu_print_str_ptr_5:
.data 0
arg_gpu_print_color_5:
.data 0
v_ptr_13:
.data 0
v_cx_14:
.data 0
v_char_15:
.data 0
arg_gpu_print_hex_x_10:
.data 0
arg_gpu_print_hex_y_10:
.data 0
arg_gpu_print_hex_val_10:
.data 0
arg_gpu_print_hex_color_10:
.data 0
v_i_16:
.data 0
v_cx_17:
.data 0
v_digit_18:
.data 0
v_char_19:
.data 0
v_base_20:
.data 0
v_count_21:
.data 0
v_key_22:
.data 0
str_1:
.data 76
.data 111
.data 114
.data 97
.data 79
.data 83
.data 32
.data 50
.data 46
.data 48
.data 32
.data 82
.data 101
.data 99
.data 111
.data 118
.data 101
.data 114
.data 121
.data 0
str_2:
.data 82
.data 101
.data 99
.data 111
.data 118
.data 101
.data 114
.data 121
.data 32
.data 101
.data 110
.data 118
.data 105
.data 114
.data 111
.data 110
.data 109
.data 101
.data 110
.data 116
.data 32
.data 105
.data 115
.data 32
.data 114
.data 117
.data 110
.data 110
.data 105
.data 110
.data 103
.data 0
str_3:
.data 80
.data 114
.data 101
.data 115
.data 115
.data 32
.data 107
.data 101
.data 121
.data 115
.data 32
.data 116
.data 111
.data 32
.data 116
.data 101
.data 115
.data 116
.data 32
.data 107
.data 101
.data 121
.data 98
.data 111
.data 97
.data 114
.data 100
.data 0
v_cursor_y_23:
.data 0
v_key_24:
.data 0
